6214-100503D Куненков Иван Лаб.3 Вар.6
itsecd/isb-3 pull request #12
Opened 2023-04-27 05:15 UTC by razzzenya

В данной л/р я реализовал опции по:
-генерации ключей шифрования
-зашифровке текста
-расшифровке текста

2023-04-27 05:41 UTC, alxmcs requested changes
Файлы с примерами данных и исходный код лежат в репозитории на одном уровне.
Хотя бы сгруппируй файлы в отдельную директорию

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +if (__name__ == "__main__"):
Лишние скобки

2023-04-27 05:41 UTC, alxmcs commented on asymmetric.py
> +    logging.info(' Asymmetric decryption was successful!')
Непоследовательное использование кавычек в строках - тут единичные, в других местах - двойные

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +    group.add_argument("-gen", "--generation",
У аргумента не настроен `action`, из-за этого он требует параметра после указания имени

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +    group.add_argument("-enc", "--encryption",
У аргумента не настроен `action`, из-за этого он требует параметра после указания имени

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +    group.add_argument("-dec", "--decryption",
У аргумента не настроен `action`, из-за этого он требует параметра после указания имени

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +        with open("settings.json") as file:
Захардкоженный путь к файлу, вынести в константы

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +        with open(args.settings) as file:
Нет обработки исключений

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +        with open("settings.json") as file:
Нет обработки исключений

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +    parser.add_argument("-set", "--settings", type=str, help="Позволяет использовать собственный json-файл с указанием "
Код подозрительно напоминает #11, c некоторыми косметическими изменениями. Изменениями, которые делают его хуже.

2023-04-27 05:41 UTC, alxmcs commented on read_functions.py
> +
Незначимая пустая строка

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +
Незначимая пустая строка

2023-04-27 05:41 UTC, alxmcs commented on main.py
> +
Незначимая пустая строка (и много где еще, дальше мне надоело размечать)

2023-04-27 05:41 UTC, alxmcs commented on read_functions.py
> +        logging.info(f" Text was successfully read from file {file_name}!")
В  #11 тоже почему-то сообщения журнала начинаются с пробела. Зачем это надо было делать - для меня загадка.
Все, что я могу сказать по поводу того, что это повторяется в данном репозитории - <img src="https://user-images.githubusercontent.com/70561974/234768949-91130836-d16c-432f-b859-579fff546002.png" height=100/>

2023-04-27 07:04 UTC, alxmcs approved these changes

2023-04-27 07:06 UTC, alxmcs requested changes
Забыл отметить:
Файлы с данными допихать в папку, лишние из репозитория убрать
![image](https://user-images.githubusercontent.com/70561974/234785699-d168a8b3-d237-42c4-a487-40b6b2d5c9b7.png)

2023-04-27 07:07 UTC, razzzenya commented
сейчас уберу!

2023-04-27 07:19 UTC, razzzenya commented
![image](https://user-images.githubusercontent.com/113578593/234788549-51d8db0e-f0f8-4f9d-a96d-df73df1d5930.png)
вот такая возникает , на чужом компе , когда дома буду зайду и удалю.

2023-04-27 11:15 UTC, razzzenya commented
Исправления загрузил

2023-04-28 08:59 UTC, alxmcs requested changes

2023-04-28 08:59 UTC, alxmcs commented on text.txt
> +Отрешившись от воззрения древних на божественное подчинение воли народа одному избранному и на подчинение этой воли божеству, история не может сделать ни одного шага без противоречия, не выбрав одног
Файл все еще на месте

2023-04-28 12:11 UTC, alxmcs approved these changes

2023-05-25 05:19 UTC, closed without merging