Ле Хань Хоанг 6213. Лаб3-вар7
itsecd/isb-3 pull request #13
Opened 2023-04-28 10:58 UTC by vieKH

Данный код позволяет

1. Генерировать ключи
2. Шифровать и дешифровать текст
3. Дешифрование данных гибридной системой
Expecto patronum

2023-05-02 06:27 UTC, alxmcs requested changes

2023-05-02 06:27 UTC, alxmcs commented on asymmetric.py
> +    ункция расшифровывает асимметрично зашифрованный текст, с помощью закрытого ключа
>ункция

2023-05-02 06:27 UTC, alxmcs commented on asymmetric.py
> +def decrypt_asym(private_key, text: bytes):
Нет тайпхинта у `private_key`  и возвращаемого значения

2023-05-02 06:27 UTC, alxmcs commented on asymmetric.py
> +def generation_asym_key():
Нет тайпхинтов

2023-05-02 06:27 UTC, alxmcs commented on functions_bonus.py
> +def load_sym_key(filename: str):
Нет тайпхинта возвращаемого значения

2023-05-02 06:27 UTC, alxmcs commented on functions_bonus.py
> +def load_text(filename: str):
Нет тайпхинта взвращаемого значения

2023-05-02 06:27 UTC, alxmcs commented on main.py
> +SETTING_FILE = 'settings.json'
Нарушение РЕР - недостаточное количество пустых строк

2023-05-02 06:27 UTC, alxmcs commented on main.py
> +if __name__ == '__main__':
Нарушение РЕР - недостаточное количество пустых строк

2023-05-02 06:27 UTC, alxmcs commented on symectric.py
> +def decrypt_sym(key: bytes, cipher_text: bytes):
Нет тайпхинта возвращаемого значения

2023-05-02 06:27 UTC, alxmcs commented on asymmetric.py
> +from cryptography.hazmat.primitives.asymmetric import rsa, padding
В данном модуле полностью отсутствует логгирование

2023-05-02 06:27 UTC, alxmcs commented on functions_bonus.py
> +from cryptography.hazmat.primitives import serialization
В данном модуле логируются только сообщения об ошибке при выпадении исключения. Лигировать успешное исполнение кода тоже нужно.

2023-05-02 06:27 UTC, alxmcs commented on main.py
> +if __name__ == '__main__':
Необходимо логировать в каком режиме запущен софт и откуда взят настройки для его работы.

2023-05-02 09:28 UTC, vieKH commented on asymmetric.py
> +from cryptography.hazmat.primitives.asymmetric import rsa, padding
Извините, я не понял ваш смысл, можете сказать удобнее

2023-05-02 10:27 UTC, alxmcs commented on asymmetric.py
> +from cryptography.hazmat.primitives.asymmetric import rsa, padding
В скрипте `asymmetric.py` никак не логируется выполнение кода, то есть никак не используется модуль `logging`

2023-05-02 10:30 UTC, alxmcs requested changes

2023-05-02 10:30 UTC, alxmcs commented on main.py
> +        if args.generation:
Все еще нет логирования того, что запущен режим генерации ключей

2023-05-02 10:30 UTC, alxmcs commented on main.py
> +        elif args.encryption:
Все еще нет логирования того, что запущен режим шифрования

2023-05-02 10:30 UTC, alxmcs commented on main.py
> +        else:
Все еще нет логирования того, что запущен режим расшифрования

2023-06-03 13:16 UTC, alxmcs commented
Зачтено

2023-06-03 13:16 UTC, closed without merging