6211-100503D Дубова Ксения Олеговна Лаб.3 Вар.4
itsecd/isb-3 pull request #15
Opened 2023-05-01 16:56 UTC by kseniaDubova

Создала графический интерфейс окна с возможностями создания ключей, шифрования/дешифрования текста с помощью алгоритма 3DES с выбором размера ключей (64/128/192 бит)

2023-05-02 06:11 UTC, alxmcs requested changes
Это далеко не самый пугающий лейаут gui, который я видел в своей жизни, но тут явно не хватает сведений о путях к файлам.

Я расшифровал текст - мне сообщили "Готово!", а где искать расшифрованный файл - нет.
![image](https://user-images.githubusercontent.com/70561974/235591797-e25fd53e-6da4-4fd5-8373-db125d3511e8.png)

2023-05-02 06:22 UTC, alxmcs requested changes
Еще одно общее замечание - в коде отсутствует логирование

2023-05-02 07:26 UTC, alxmcs requested changes
`.DS_Store` убрать из репозитория

2023-05-02 07:26 UTC, alxmcs commented on main_w.py
> +    def cleak_key(self) -> None:
Я подозреваю, что имелся в виду `click`

2023-05-02 07:26 UTC, alxmcs commented on main_w.py
> +    def cleak_encryption(self) -> None:
Я подозреваю, что имелся в виду `click`

2023-05-02 07:26 UTC, alxmcs commented on main_w.py
> +    def cleak_decryption(self) -> None:
Я подозреваю, что имелся в виду `click`

2023-05-02 07:29 UTC, alxmcs commented on requirements.txt
> +anyio==3.6.2
Файл все еще содержит все библиотеки на свете, кроме нужных

2023-05-03 08:45 UTC, kseniaDubova commented
pip freeze так и выводит то, что лежит в файле

2023-05-03 09:17 UTC, alxmcs requested changes
Я бы настоятельно порекомендовал удостовериться, что `pip freeze` вызывается именно в том виртуальном окружении, в котором исполняется проект.

Третье ревью подряд не можешь с этим разобраться.

2023-05-07 10:06 UTC, alxmcs approved these changes

2023-05-30 05:35 UTC, closed without merging