Богачев Матвей Иванович 6211
itsecd/isb-3 pull request #16
Opened 2023-05-03 06:29 UTC by Matosik

2023-05-03 10:08 UTC, alxmcs requested changes
Общие замечания:
* у кода отсутствует физическая декомпозиция полностью, он навален в одном файле исходного кода,
* логическая декомпозиция кода слабая - выделен один-единственный класс, который выполняет работу с обоими видами шифрования, при этом часть функционала по работе с криптографией фигурирует внутри меню. Меню при этом реализовано в виде двух функций вне какой-либо объектной модели.
* текстовое меню должно прекратить свое существование,
* я практически прекратил свое существование после чтения текстовых сообщений, выводимых софтом.

2023-05-03 10:08 UTC, alxmcs commented on main.py
> +    time.sleep(2)
Использовать эту функцию для создания искусственного времени ожидания ответа софта - грех

2023-05-03 10:08 UTC, alxmcs commented on main.py
> +class HybridEncryption:
В классе отсутствует логирование выполняемых методов

2023-05-03 10:08 UTC, alxmcs commented on main.py
> +def menu():
Как было указано в одном из комментариев выше, такой способ получения параметров от пользователя неприемлем в конце 2 курса.

2023-05-12 09:11 UTC, Matosik commented
исправил

2023-05-15 12:37 UTC, alxmcs requested changes

2023-05-15 15:09 UTC, Matosik commented
> то есть если у меня есть готовые ключи и текст я запускаю код и передаю путь до ключа и шифрую/дешифрую текст ?

2023-05-19 14:13 UTC, alxmcs commented on main.py
> +        self.decryption_button.show()
Претензия с прошлого ревью не устранена

2023-05-19 14:37 UTC, Matosik commented
но у пользователя спрашивается для начала длина ключа, который он хочет создать или уже существующего ключ, после этого пользователь может зашифровать\расшифровать текст. Почему так нельзя я не понимаю

2023-05-19 14:41 UTC, Matosik commented
я могу, кончено, сделать так, чтобы все кнопки были открыты, но пользователь не может зашировать данные если программа еще не видела его ключей

2023-05-20 08:16 UTC, alxmcs requested changes

2023-05-20 08:16 UTC, alxmcs commented on main.py
> +        self.enycryption_button.show()
Ладно, допустим, что часть ui будет изначально скрыта

2023-05-20 08:16 UTC, alxmcs commented on main.py
> +    def decryption(self) -> None:
Но в данном методе мне крайне не нравится то, что у пользователя нет возможности указать путь к файлу, который он хочет расшифровать

2023-05-20 08:16 UTC, alxmcs commented on symmetric.py
> +            'encrypted_file': os.path.join(self.way, 'encrypted_file.txt'),
Потому что путь к нему захардкожен внутри этого класса

2023-05-20 08:16 UTC, alxmcs commented on symmetric.py
> +            'iv_path': os.path.join(self.way, 'iv_path.txt')
Как и путь к синхрометке блочного режима

2023-05-20 08:16 UTC, alxmcs commented on symmetric.py
> +            with open(self.settings['encrypted_file'], 'rb') as f:
Что максимально неудачное ux решение, если пользователю требуется только расшифровать полученный им из стороннего источника шифротекст, который может не лежать по этому захардкоженному пути.

2023-05-21 11:39 UTC, Matosik commented on symmetric.py
> +            with open(self.settings['encrypted_file'], 'rb') as f:
Вы же согласны со мной, что для расшифрования текста нужны ключи для шифрования? В этой программе пользователю предлагается либо создать ключи и с помощью них зашифровать выбранный текст, либо выбрать уже готовые ключи и файл, который нужно расшифровать тем самым когда пользователь выбирает ключи он выбирает и зашифрованный текст и после нажатия кнопки "Decode the text" этот текст, который лежит у пользователя в папке с ключами будет расшифрован.

2023-05-21 11:39 UTC, Matosik commented
Вы же согласны со мной, что для расшифрования текста нужны ключи для шифрования? В этой программе пользователю предлагается либо создать ключи и с помощью них зашифровать выбранный текст, либо выбрать уже готовые ключи и файл, который нужно расшифровать тем самым когда пользователь выбирает ключи он выбирает и зашифрованный текст и после нажатия кнопки "Decode the text" этот текст, который лежит у пользователя в папке с ключами будет расшифрован.

2023-05-22 10:20 UTC, alxmcs requested changes
То, каким образом сейчас построено взаимодействие твоего кода с пользователем - дерьмовый ux. Человек, который вынужден пользоваться твоим софтом, испытывает при этом невыносимые страдания. Потому что для того, чтобы расшифровать текст имеющимися у него ключами, ему нужно скопировать шифротекст в определенную папку (которую в гуях нигде посмотреть нельзя после выбора) и переименовать файл, чтобы он имел специфическое название и специфическое расширение, о которых ему никак нигде явно не сообщается.
Не надо убеждать меня в том, что это и так сойдет. Исправь это недоразумение наконец.

Ужасаясь ущербностью ux твоего софта, я немного упустил из виду проблемы  непосредственно кода. Так что вот новые замечания.

2023-05-22 10:20 UTC, alxmcs commented on main.py
> +        self.enycryption_button = QPushButton('Encrypt the text', self)
>enycryption_button 
Опечатка

2023-05-22 10:20 UTC, alxmcs commented on main.py
> +    def size_selection(self, text: str) -> None:
Нарушение РЕР - недостаточное число пустых строк

2023-05-22 10:20 UTC, alxmcs commented on main.py
> +        self.size = int(re.findall('(\d+)', text)[0])//8
Атрибут объявляется вне инициализатора

2023-05-22 10:20 UTC, alxmcs commented on main.py
> +        self.key = Hybrid_Cryptosystem(self.size, way)
Атрибут объявляется вне инициализатора

2023-05-22 10:20 UTC, alxmcs commented on main.py
> +        self.key = Hybrid_Cryptosystem(self.size, way)
Атрибут объявляется вне инициализатора

2023-05-22 14:21 UTC, Matosik commented
в новой версии софта было выбрано решение делать всё через json файл

2023-05-22 14:23 UTC, Matosik commented
надеюсь я хоть немного в новой версии приблизился к тому что Вы хотели видеть

2023-05-22 14:28 UTC, Matosik commented
![image](https://github.com/itsecd/isb-3/assets/113327388/edf98405-28f9-47b9-9f0d-f2bbf8b5f397)

2023-05-22 15:39 UTC, alxmcs approved these changes
Думаю, в таком виде код можно принять.



>Хотя некоторые претензии к коду остались неисправленными

2023-05-30 06:03 UTC, closed without merging