6211-100503D Кадников Егор Вадимович Лабораторная работа 3, Вариант 7
itsecd/isb-3 pull request #18
Opened 2023-05-04 13:29 UTC by acebiscuits

От меня требовалось реализовать приложение, которое будет выполнять три указанных ниже сценарии:

Генерация ключей гибридной системы
1.1. Сгенерировать ключ для симметричного алгоритма.
1.2. Сгенерировать ключи для ассиметричного алгоритма.
1.3. Сериализовать ассиметричные ключи.
1.4. Зашифровать ключ симметричного шифрования открытым ключом и сохранить по указанному пути.

Шифрование данных гибридной системой
2.1. Расшифровать симметричный ключ.
2.2. Зашифровать текст симметричным алгоритмом и сохранить по указанному пути.

Дешифрование данных гибридной системой.
3.1. Расшифровать симметричный ключ.  
3.2. Расшифровать текст симметричным алгоритмом и сохранить по указанному пути. 

В качестве алгоритма симметричного шифрования я выбрал SM4

2023-05-04 13:43 UTC, alxmcs requested changes
Общее замечание - явно не самая удачная декомпозиция кода, но, в целом, терпимая.

2023-05-04 13:43 UTC, alxmcs commented on decrypting.py
> +    #key0 = SM4Key(sym_key)
Закомменченные фрагменты кода убрать

2023-05-04 13:43 UTC, alxmcs commented on decrypting.py
> +    #deser_text = stj.deserialisation_from_json(settings['encrypted_file'])
Закомменченные фрагменты кода убрать

2023-05-04 13:43 UTC, alxmcs commented on lab3.py
> +    print(args)
`print` убрать или заменить на логирование

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +                #print(enc_text)
Закомменченные фрагменты кода убрать

2023-05-04 13:43 UTC, alxmcs commented on generating_keys.py
> +    # сериализация закрытого ключа в файл
Комменты вне докстрингов убрать

2023-05-04 13:43 UTC, alxmcs commented on decrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on decrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on generating_keys.py
> +
Незначимые пустые строки убрать

2023-05-04 13:43 UTC, alxmcs commented on generating_keys.py
> +    # сериализация открытого ключа в файл
Комменты вне докстрингов убрать

2023-05-04 13:43 UTC, alxmcs commented on serialisation_to_json.py
> +
Нарушение РЕР - недостаточное количество пустых строк

2023-05-04 13:43 UTC, alxmcs commented on serialisation_to_json.py
> +
Нарушение РЕР - недостаточное количество пустых строк

2023-05-04 13:43 UTC, alxmcs commented on generating_keys.py
> +
Нарушение РЕР - недостаточное количество пустых строк

2023-05-04 13:43 UTC, alxmcs commented on encrypting.py
> +
Нарушение РЕР - недостаточное количество пустых строк

2023-05-05 14:20 UTC, acebiscuits commented on encrypting.py
> +
после импортов нужно по 2 пустые строки?

2023-05-07 10:08 UTC, alxmcs approved these changes

2023-05-16 05:27 UTC, closed without merging