6213-100503D Панюшкин Андрей Михайлович, Л.Р№3, вар 14(6)
itsecd/isb-3 pull request #2
Opened 2023-04-05 14:11 UTC by Santas7

* Я немного перепутал и сделал 6 вариант из 9 которые были предложены ( SEED ).
Лабораторная работа номер 3 - гибридная криптосистема сочетающая  себе преимущества симметричных и асимметричных алгоритмов шифрования.

## Мною было создано основное меню программы которое включает следующие пункты:

1. генерация ключей шифрования
2. шифрование данных
3. де шифрование данных

Каждый пункт очень важен и включает в себя еще другие под пункты.
## Для генерации ключей это:

1. Генерация ключа для симметричного алгоритма.
2. Генерация ключей для асимметричного алгоритма.
3. Сериализация асимметричных ключей.
4. Зашифровка ключа симметричного шифрования открытым ключом и сохранение по указанному пути.

## Для шифрования данных это:

1. Расшифровка симметричного ключа.
2. Зашифровка текста симметричным алгоритмом и сохранение по указанному пути.

## Для де шифрования данных это:

1. Расшифровка симметричного ключа.
2. Расшифровка текста симметричным алгоритмом и сохранение по указанному пути.

## Микро-вывод по лабораторной работе
Я выполнил все условия лабораторной работы, получил успех в шифровании и де шифровании данных.

2023-04-07 09:04 UTC, alxmcs requested changes
Общие замечания:

* Меня очень расстраивает, что вместо грамотно составленной структуры классов для решения поставленных в лабораторной задач, я наблюдаю три хромые функции.
* Наличие хоть какой-то логической декомпозиции кода - это отрадно, не хватает физической.
* Интерфейс в виде текстового меню - оскорбление всех преподавателей, причастных к курсу прикладного программирования, который был в прошлом семестре. Я был в их числе.
* Какой-либо сигнализации о работе софта в коде нет - ни логгинга, ни tqdm, ничего.
* Обработки потенциальных исключений в коде тоже нет.
* Примеров работы софта в виде файлов с ключами, файла с шифротекстом (достаточного объема) и результатом дешифрации тоже нет.

2023-04-09 15:38 UTC, Santas7 commented on main.py
> +    with open(public_key_path, 'wb') as f:
исправил это

2023-04-09 19:16 UTC, Santas7 commented
исправил все что вы сказали, сделал класс, добавил исключения, проверку путей, сделал приложение с использованием PyQt6, прикрепил файлы

2023-04-10 06:46 UTC, alxmcs requested changes
Общее замечание: разлепи уже наконец сущность, отвечающую за логику работы своего приложения (криптографию) от сущности, отвечающей за  графический интерфейс и размести их в разных классах и разных файлах с исходниками.

2023-04-10 06:46 UTC, alxmcs commented on main.py
> +        # Считывание зашифрованного ключа симметричного шифрования из файла
Этот кусок кода фигурирует у тебя в исходнике два раза в совершенно идентичном виде. Было бы логично выделить его в отдельный метод.

2023-04-10 06:46 UTC, alxmcs commented on main.py
> +        # Считывание зашифрованного ключа симметричного шифрования из файла
В комментарии выше я имел в виду это место

2023-04-10 06:46 UTC, alxmcs commented on main.py
> +        # Расшифровка ключа симметричного шифрования закрытым ключом
Для этого фрагмента аналогично - он есть тут

2023-04-10 06:46 UTC, alxmcs commented on main.py
> +        # Расшифровка ключа симметричного шифрования закрытым ключом
И тут

2023-04-10 07:14 UTC, alxmcs commented
Приблизительно

2023-04-10 07:23 UTC, Santas7 commented
исправил

2023-04-10 07:50 UTC, alxmcs approved these changes
Думаю, в таком виде код можно принять

2023-04-29 04:52 UTC, closed without merging