6211 Чумаков Иван Игоревич Лаб.3 Вар.8
itsecd/isb-3 pull request #20
Opened 2023-05-07 19:14 UTC by mestromezer

In this lab I was supposed to create a hybrid encryption system. The thing is that we must use assym algorithms to cipher symm key with which we can encrypt big amounts of data much faster and more safely.

2023-05-09 08:27 UTC, alxmcs commented on ASSymmetricChipher.py
> +        with open(self.private_pem, 'wb') as file_out:
Нет обработки исключений

2023-05-09 08:27 UTC, alxmcs commented on ASSymmetricChipher.py
> +        with open(pem, 'rb') as pem_in:
Нет обработки исключений

2023-05-09 08:27 UTC, alxmcs commented on ASSymmetricChipher.py
> +        with open(self.ciphed_file, 'wb') as file:
Нет обработки исключений

2023-05-09 08:27 UTC, alxmcs commented on ASSymmetricChipher.py
> +        with open(self.decrypted_file, 'wb') as file:
Нет обработки исключений

2023-05-09 08:27 UTC, alxmcs commented on ASSymmetricChipher.py
> +        with open(self.ciphed_file, 'rb') as file:
Нет обработки исключений

2023-05-09 08:28 UTC, alxmcs commented on ASSymmetricChipher.py
> +            d_public_key = load_pem_public_key(public_bytes)
Этот код уже не требует наличия открытого фалового потока

2023-05-09 08:29 UTC, alxmcs commented on ASSymmetricChipher.py
> +            return c_text
Этот код уже не требует наличия открытого фалового потока

2023-05-09 08:29 UTC, alxmcs commented on ASSymmetricChipher.py
> +            private_key = load_pem_private_key(private_bytes, password=None,)
Этот код уже не требует наличия открытого фалового потока

2023-05-09 08:29 UTC, alxmcs commented on FirstScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:30 UTC, alxmcs commented on FirstScenary.py
> +# 1. Генерация ключей гибридной системы
Комменты вне докстрингов убрать

2023-05-09 08:30 UTC, alxmcs commented on FirstScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:30 UTC, alxmcs commented on FirstScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:30 UTC, alxmcs commented on SecondScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:30 UTC, alxmcs commented on SecondScenary.py
> +# 2. Шифрование данных гибридной системой
Комменты вне докстрингов убрать

2023-05-09 08:30 UTC, alxmcs commented on SecondScenary.py
> +        return data
Этот код уже не требует наличия открытого фалового потока

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +    # symmetric_key_decrypted = "./DECRYPTED_DATA/symmetric_key_decrypted"
Закомменченный код убрать

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +    # Ассиметричный для симетричного
Комменты вне докстрингов убрать

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +    # Симметричный для текста
Комменты вне докстрингов убрать

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:31 UTC, alxmcs commented on SecondScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:31 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:32 UTC, alxmcs commented on SymmetricChipher.py
> +        # Remove any padding from the plaintext
Комменты вне докстрингов убрать

2023-05-09 08:32 UTC, alxmcs commented on SymmetricChipher.py
> +    def __de_padd(self, plaintext):
Нет докстринга

2023-05-09 08:32 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:32 UTC, alxmcs commented on SymmetricChipher.py
> +        # Extract the initialization vector from the ciphertext
Комменты вне докстрингов убрать

2023-05-09 08:32 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +        # Create a Blowfish cipher object
Комменты вне докстрингов убрать

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +    def __dump_plaintext(self, text: str) -> None:
Нет докстринга

2023-05-09 08:33 UTC, alxmcs commented on SymmetricChipher.py
> +        with open(self.decrypt_file, "wb") as file:
Нет обработки исключений

2023-05-09 08:34 UTC, alxmcs commented on SymmetricChipher.py
> +        with open(self.encrypt_file, "wb") as file:
Нет обработки исключений

2023-05-09 08:34 UTC, alxmcs commented on SymmetricChipher.py
> +        with open(self.decrypt_file, 'r') as file:
Нет обработки исключений

2023-05-09 08:34 UTC, alxmcs commented on SymmetricChipher.py
> +        with open(self.sym_key_file, mode='rb') as key_file:
Нет обработки исключений

2023-05-09 08:34 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:35 UTC, alxmcs commented on SymmetricChipher.py
> +
Незначимую пустую строку убрать

2023-05-09 08:36 UTC, alxmcs commented on SymmetricChipher.py
> +    def __init__(self, size: int, sym_key_file: str, encrypt_file: str = None, decrypt_file: str = None):
Нет докстринга

2023-05-09 08:36 UTC, alxmcs commented on SymmetricChipher.py
> +            # key_file.write(b"\n")
Закомменченный код убрать

2023-05-09 08:37 UTC, alxmcs commented on ThirdScenary.py
> +# 3. Дешифрование данных гибридной системой
Комменты вне докстринга убрать

2023-05-09 08:37 UTC, alxmcs commented on ThirdScenary.py
> +    # Ассиметричный для симетричного
Комменты вне докстринга убрать

2023-05-09 08:37 UTC, alxmcs commented on ThirdScenary.py
> +
Незначимую пустую строку убрать

2023-05-09 08:37 UTC, alxmcs commented on ThirdScenary.py
> +    # Симметричный для текста
Комменты вне докстринга убрать

2023-05-09 08:37 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:38 UTC, alxmcs commented on main.py
> +    # mode = (False, False, True)
Закомменченный код убрать

2023-05-09 08:38 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:38 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:39 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:39 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:39 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:39 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:39 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:40 UTC, alxmcs commented on main.py
> +
Незначимую пустую строку убрать

2023-05-09 08:41 UTC, alxmcs commented on main.py
> +    parser = argparse.ArgumentParser()
Нет аргумента, позволяющего пользователю указать путь к собственному файлу с конфигом

2023-05-10 18:03 UTC, alxmcs requested changes
Все еще остались не приведенными в соотвестствие с РЕР название модулей `FirstScenary` и т.д. Во-первых, модули не именуются паскаль кейсом, во-вторых, название модуля должно отражать его функционал.

2023-05-11 06:20 UTC, mestromezer commented
Внес требуемые изменения

2023-05-12 12:24 UTC, alxmcs commented
Если все изменения внесены, то ![image](https://github.com/itsecd/isb-3/assets/70561974/d7651151-1b6c-43cc-be6f-cb583e07100e)

2023-05-13 09:48 UTC, alxmcs approved these changes

2023-05-30 05:35 UTC, closed without merging