Сысолятин Егор Максимович 6212-100503D, 4 Вариант.
itsecd/isb-3 pull request #29
Opened 2023-05-15 18:07 UTC by RYTpL

In this laboratory work, in the end, I got a hybrid cryptosystem - combining the advantages of symmetric and asymmetric encryption algorithms and, in general, even resembling systems used in practice.

It will work as follows: the message is encrypted using a symmetric algorithm, and the key of the symmetric algorithm is asymmetric. RSA will be used as an asymmetric algorithm, the symmetric algorithm is selected according to the option.

2023-05-16 08:12 UTC, alxmcs requested changes

2023-05-16 08:12 UTC, alxmcs commented on main.py
> +    def run(self):
Для взаимодейсвия с пользователем либо используй `argparse`, либо `pyqt`. Делать текстовое меню в конце 2 курса - харам

2023-05-16 08:12 UTC, alxmcs commented on code.py
> +class Encryption:
Этот класс нарушает srp, из него нужно выделить еще два класса - для работы с симметричным шифром и для работы с ассиметричным.

Обитать они должны, очевидно, в отдельных скриптах.

2023-05-19 20:46 UTC, RYTpL commented
did and fixed it

вт, 16 мая 2023 г., 12:15 PM alxmcs ***@***.***>:

> Assigned #29 <https://github.com/itsecd/isb-3/pull/29> to @RYTpL
> <https://github.com/RYTpL>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/itsecd/isb-3/pull/29#event-9254901981>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3FJNHCV3SO3BGIXRSBNOS3XGMZSVANCNFSM6AAAAAAYCRN2DY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-20 08:33 UTC, alxmcs requested changes
Это первая попытка организовать наследование классов в решении данной лабораторной. Попытка достойна уважения, только она неудачная.

Если бы я реализовывал что-то подобное, то остановился бы на примерно следующем:

`Encryption` оставил бы абстрактным с тремя методами - генерации ключей, шифрованием, дешифрованием.
Соорудил бы два наследника - `SymmetricEncryption` и `AsymmetricEncryption`, каждый из которых реализовывал бы три родительских метода.
И класс `HybridCryptosystem`, который имел бы в качестве атрибутов по объекту `SymmetricEncryption` и `AsymmetricEncryption` и занимался бы парсингом настроек из жсона и выполнением 3х режимов работы из задания.

2023-05-20 08:33 UTC, alxmcs commented on code.py
> +# symmetric_encryption
Вынести в отдельный модуль

2023-05-20 08:33 UTC, alxmcs commented on code.py
> +# asymmetric_encryption
Вынести в отдельный модуль

2023-05-20 08:33 UTC, alxmcs commented on code.py
> +    def encrypt(self) -> None:
Потрясяющий наследник базового класса - никаких имплементаций

2023-05-20 08:33 UTC, alxmcs commented on code.py
> +        cipher = Cipher(algorithms.TripleDES(symmetric_key), modes.CBC(iv))
Потому что реализация симметричного шифрования находится в классе `AsymmetricEncryption`

2023-05-20 08:33 UTC, alxmcs commented on code.py
> +class AsymmetricEncryption(Encryption):
Из чего можно сделать очевидный вывод - это дерьмая декомпозиция, ее надо переделать

2023-05-20 08:33 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
Убрать код под `if __name__ == "__main__":`

2023-05-20 08:33 UTC, alxmcs commented on main.py
> +parser.add_argument('-g', '--generate', action='store_true', help='Generate keys and save them in a directory')
Вынести аргументы, отвечающие за запуск режимов в mutual exclusive group

2023-05-29 11:42 UTC, alxmcs requested changes

2023-05-29 11:42 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
Замечание с прошлого ревью не исправлено

2023-05-29 11:42 UTC, alxmcs commented on main.py
> +parser.add_argument('-g', '--generate', action='store_true', help='Generate keys and save them in a directory')
Замечание с прошлого ревью не исправлено

2023-05-30 05:52 UTC, alxmcs requested changes

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
В третий раз: убрать код под `if __name__ == "__main__":`

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +# Create a mutually exclusive group for the modes
Убрать комменты

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +# Parse the arguments
Убрать комменты

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +# symmetric_encryption
Убрать комменты вне докстрингов

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +from encryption import Encryption
Импорт перенести в начало скрипта

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +# asymmetric_encryption
Убрать комменты вне докстрингов

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +from encryption import Encryption
Импорт перенести в начало скрипта

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +class SymmetricEncryption(Encryption):
Класс вынести в отдельный модуль

2023-05-30 05:52 UTC, alxmcs commented on workspace.py
> +class AsymmetricEncryption(Encryption):
Класс вынести в отдельный модуль

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +parser.add_argument('-e', '--encrypt', type=str, help='Encrypt a text file')
Я бы поинтересовался, зачем здесь этот код, но не буду. Убрать это отсюда.

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +parser.add_argument('-d', '--decrypt', type=str, help='Decrypt a text file')
Аналогично

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +    print('Keys generated and saved')
Заменить на logging

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +    print('Text encrypted and saved')
Заменить на logging

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +    print('Text decrypted:')
Заменить на logging

2023-05-30 05:52 UTC, alxmcs commented on main.py
> +    print(way)
Заменить на logging

2023-05-30 18:22 UTC, RYTpL commented
все

вт, 30 мая 2023 г. в 09:52, alxmcs ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209730728>:
>
> > @@ -0,0 +1,47 @@
> +import re
> +import sys
> +import argparse
> +from workspace import Encryption as en
> +
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
>
> В третий раз: убрать код под if __name__ == "__main__":
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209730851>:
>
> > @@ -0,0 +1,47 @@
> +import re
> +import sys
> +import argparse
> +from workspace import Encryption as en
> +
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
> +
> +parser.add_argument('-s', '--size', type=int, choices=[64, 128, 192], help='Choose the key size in bits')
> +
> +# Create a mutually exclusive group for the modes
>
> Убрать комменты
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209730890>:
>
> > +import re
> +import sys
> +import argparse
> +from workspace import Encryption as en
> +
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
> +
> +parser.add_argument('-s', '--size', type=int, choices=[64, 128, 192], help='Choose the key size in bits')
> +
> +# Create a mutually exclusive group for the modes
> +group = parser.add_mutually_exclusive_group(required=True)
> +group.add_argument('-g', '--generate', action='store_true', help='Generate keys and save them in a directory')
> +group.add_argument('-e', '--encrypt', action='store_true', help='Encrypt a file using the keys')
> +group.add_argument('-d', '--decrypt', action='store_true', help='Decrypt a file using the keys')
> +
> +# Parse the arguments
>
> Убрать комменты
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209731549>:
>
> > +            'encrypted_file': os.path.join(self.way, 'encrypted_file.txt'),
> +            'decrypted_file': os.path.join(self.way, 'decrypted_file.txt'),
> +            'iv_path': os.path.join(self.way, 'iv_path.txt')
> +        }
> +
> +    @abc.abstractmethod
> +    def encrypt(self) -> None:
> +        """Encrypt data."""
> +        pass
> +
> +    @abc.abstractmethod
> +    def decrypt(self) -> None:
> +        """Decrypt data."""
> +        pass
> +
> +# symmetric_encryption
>
> Убрать комменты вне докстрингов
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209731731>:
>
> > +            'decrypted_file': os.path.join(self.way, 'decrypted_file.txt'),
> +            'iv_path': os.path.join(self.way, 'iv_path.txt')
> +        }
> +
> +    @abc.abstractmethod
> +    def encrypt(self) -> None:
> +        """Encrypt data."""
> +        pass
> +
> +    @abc.abstractmethod
> +    def decrypt(self) -> None:
> +        """Decrypt data."""
> +        pass
> +
> +# symmetric_encryption
> +from encryption import Encryption
>
> Импорт перенести в начало скрипта
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209731830>:
>
> > +from encryption import Encryption
> +
> +class SymmetricEncryption(Encryption):
> +    """Class for symmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['symmetric_key'] = os.path.join(self.way, 'symmetric_key.txt')
> +
> +    def encrypt(self) -> None:
> +        pass
> +
> +    def decrypt(self) -> None:
> +        pass
> +
> +# asymmetric_encryption
>
> Убрать комменты вне докстрингов
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209731922>:
>
> > +
> +class SymmetricEncryption(Encryption):
> +    """Class for symmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['symmetric_key'] = os.path.join(self.way, 'symmetric_key.txt')
> +
> +    def encrypt(self) -> None:
> +        pass
> +
> +    def decrypt(self) -> None:
> +        pass
> +
> +# asymmetric_encryption
> +from encryption import Encryption
>
> Импорт перенести в начало скрипта
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209732155>:
>
> > +        }
> +
> +    @abc.abstractmethod
> +    def encrypt(self) -> None:
> +        """Encrypt data."""
> +        pass
> +
> +    @abc.abstractmethod
> +    def decrypt(self) -> None:
> +        """Decrypt data."""
> +        pass
> +
> +# symmetric_encryption
> +from encryption import Encryption
> +
> +class SymmetricEncryption(Encryption):
>
> Класс вынести в отдельный модуль
> ------------------------------
>
> In workspace.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209732261>:
>
> > +    """Class for symmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['symmetric_key'] = os.path.join(self.way, 'symmetric_key.txt')
> +
> +    def encrypt(self) -> None:
> +        pass
> +
> +    def decrypt(self) -> None:
> +        pass
> +
> +# asymmetric_encryption
> +from encryption import Encryption
> +
> +class AsymmetricEncryption(Encryption):
>
> Класс вынести в отдельный модуль
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209733147>:
>
> > +import argparse
> +from workspace import Encryption as en
> +
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
> +
> +parser.add_argument('-s', '--size', type=int, choices=[64, 128, 192], help='Choose the key size in bits')
> +
> +# Create a mutually exclusive group for the modes
> +group = parser.add_mutually_exclusive_group(required=True)
> +group.add_argument('-g', '--generate', action='store_true', help='Generate keys and save them in a directory')
> +group.add_argument('-e', '--encrypt', action='store_true', help='Encrypt a file using the keys')
> +group.add_argument('-d', '--decrypt', action='store_true', help='Decrypt a file using the keys')
> +
> +# Parse the arguments
> +args = parser.parse_args()
> +parser.add_argument('-e', '--encrypt', type=str, help='Encrypt a text file')
>
> Я бы поинтересовался, зачем здесь этот код, но не буду. Убрать это отсюда.
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209733338>:
>
> > +from workspace import Encryption as en
> +
> +parser = argparse.ArgumentParser(description='A program for 3DES encryption and decryption')
> +
> +parser.add_argument('-s', '--size', type=int, choices=[64, 128, 192], help='Choose the key size in bits')
> +
> +# Create a mutually exclusive group for the modes
> +group = parser.add_mutually_exclusive_group(required=True)
> +group.add_argument('-g', '--generate', action='store_true', help='Generate keys and save them in a directory')
> +group.add_argument('-e', '--encrypt', action='store_true', help='Encrypt a file using the keys')
> +group.add_argument('-d', '--decrypt', action='store_true', help='Decrypt a file using the keys')
> +
> +# Parse the arguments
> +args = parser.parse_args()
> +parser.add_argument('-e', '--encrypt', type=str, help='Encrypt a text file')
> +parser.add_argument('-d', '--decrypt', type=str, help='Decrypt a text file')
>
> Аналогично
> ------------------------------
>
> In main.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1209735702>:
>
> > +args = parser.parse_args()
> +
> +if args.size:
> +
> +    key = en(args.size)
> +else:
> +
> +    key = en()
> +
> +
> +if args.generate:
> +
> +    way = input('Enter the directory to save the keys: ')
> +
> +    key.generation_key(way)
> +    print( [...]

2023-05-31 07:06 UTC, alxmcs requested changes

2023-05-31 07:06 UTC, alxmcs commented on asymmetric_encryption.py
> +class AsymmetricEncryption(Encryption):
Сейчас в твоем коде происходит следующее:
* класс `Encryption` абстрактный, объявляет два метода - `decrypt` и `encrypt`.
* класс `SymmetricEncryption` отнаследован от `Encryption`, не имплементирует ничего из его методов.
* класс `AsymmetricEncryption` отнаследован от `Encryption`, не имплементирует ничего из его методов, имеет говнометоды, в которых намешаны оба вида шифрования.

Если ты считаешь, что это хорошая декомпозиция классов для выполнения поставленной задачи, то могу посоветовать пройти курс уколов галоперидолом.

Для самых маленьких и тупых пишу как должно быть, чтобы не нарушалась половина SOLID-принципов:
* класс `Encryption` абстрактный, объявляет два метода - `decrypt`, `encrypt`, `generate_key`.
* класс `SymmetricEncryption` отнаследован от Encryption,  имплементирует методы `decrypt`, `encrypt`, `generate_key` для 3DES.
* класс `AsymmetricEncryption` отнаследован от Encryption, имплементирует методы `decrypt`, `encrypt`, `generate_key` для RSA.
* класс `HybridCryptosystem` имеет в качестве атрибутов экземпляр `SymmetricEncryption` и `AsymmetricEncryption` и имеет методы для выполнения режимов работы, заявленных в условии лабораторной.

2023-06-02 17:15 UTC, RYTpL commented
Я понял, какую чушь там написал и решил забыть это как страшный сон, я
полностью переписал лабу и понял как ее сделать проще

ср, 31 мая 2023 г. в 11:07, alxmcs ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In asymmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211167596>:
>
> > +from cryptography.hazmat.primitives import hashes
> +from cryptography.hazmat.primitives import padding as sym_padding
> +from cryptography.hazmat.primitives import serialization
> +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class AsymmetricEncryption(Encryption):
> +    """Class for asymmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['public_key'] = os.path.join(self.way, 'public_key.txt')
> +        self.settings['private_key'] = os.path.join(self.way, 'private_key.txt')
> +
> +    def encrypt(self) -> None:
>
> Потрясающая имплементация метода базового класса
> ------------------------------
>
> In asymmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211167687>:
>
> > +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class AsymmetricEncryption(Encryption):
> +    """Class for asymmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['public_key'] = os.path.join(self.way, 'public_key.txt')
> +        self.settings['private_key'] = os.path.join(self.way, 'private_key.txt')
> +
> +    def encrypt(self) -> None:
> +        pass
> +
> +    def decrypt(self) -> None:
>
> Как и эта
> ------------------------------
>
> In symmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211167755>:
>
> > +
> +from cryptography.hazmat.primitives import hashes
> +from cryptography.hazmat.primitives import padding as sym_padding
> +from cryptography.hazmat.primitives import serialization
> +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class SymmetricEncryption(Encryption):
> +    """Class for symmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['symmetric_key'] = os.path.join(self.way, 'symmetric_key.txt')
> +
> +    def encrypt(self) -> None:
>
> Как и эта
> ------------------------------
>
> In symmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211167794>:
>
> > +from cryptography.hazmat.primitives import serialization
> +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class SymmetricEncryption(Encryption):
> +    """Class for symmetric encryption."""
> +
> +    def __init__(self, size: int, way: str) -> None:
> +        super().__init__(size, way)
> +        self.settings['symmetric_key'] = os.path.join(self.way, 'symmetric_key.txt')
> +
> +    def encrypt(self) -> None:
> +        pass
> +
> +    def decrypt(self) -> None:
>
> Как и эта
> ------------------------------
>
> In asymmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211168797>:
>
> > +                    f.read(), password=None)
> +        except OSError as err:
> +            logging.warning(
> +                f"{err} error when writing to a file {self.settings['private_key']}")
> +        try:
> +            with open(self.settings['symmetric_key'], "rb") as f:
> +                encrypted_symmetric_key = f.read()
> +            symmetric_key = private_key.decrypt(encrypted_symmetric_key, padding.OAEP(
> +                mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None))
> +        except OSError as err:
> +            logging.warning(
> +                f"{err} error when writing to a file {self.settings['symmetric_key']}")
> +        return symmetric_key
> +
> +
> +    def encryption(self, way: str) -> None:
>
> Зачем ты наследовал от базового класса две сущности для симметричного и
> ассиметричного шифрования, если в этом классе у тебя навалено оба вида
> шифрования...
> ------------------------------
>
> In symmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211169129>:
>
> > @@ -0,0 +1,22 @@
> +import logging
> +import os
> +
> +from cryptography.hazmat.primitives import hashes
> +from cryptography.hazmat.primitives import padding as sym_padding
> +from cryptography.hazmat.primitives import serialization
> +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class SymmetricEncryption(Encryption):
>
> ...а здесь вообще ничего нихера нет?
> ------------------------------
>
> In asymmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211170819>:
>
> > +        except OSError as err:
> +            logging.warning(
> +                f"{err} error when writing to a file {self.settings['iv_path']}")
> +        try:
> +            with open(self.settings['encrypted_file'], 'wb') as f_text:
> +                f_text.write(c_text)
> +        except OSError as err:
> +            logging.warning(
> +                f"{err} error when writing to a file {self.settings['encrypted_file']}")
> +        else:
> +            logging.info("The text is encrypted")
> +
> +
> +    def decryption(self) -> str:
> +        """
> +       3DES algorithm text decryption function
>
> Что 3DES забыл в классе под названием AsymmetricEncryption?
> ------------------------------
>
> In asymmetric_encryption.py
> <https://github.com/itsecd/isb-3/pull/29#discussion_r1211186629>:
>
> > @@ -0,0 +1,156 @@
> +import logging
> +import os
> +
> +from cryptography.hazmat.primitives import hashes
> +from cryptography.hazmat.primitives import padding as sym_padding
> +from cryptography.hazmat.primitives import serialization
> +from cryptography.hazmat.primitives.asymmetric import padding, rsa
> +from cryptography.hazmat.primitives.ciphers import (Cipher, algorithms, modes)
> +from encryption import Encryption
> +
> +class AsymmetricEncryption(Encryption):
>
> Сейчас в твоем коде происходит следующее:
>
>    - класс Encryption абстрактный, объявляет два метода - decrypt и
>    encrypt.
>    - класс SymmetricEncryption отнаследован от Encryption, не
>    имплементирует ничего из его методов.
>    - класс AsymmetricEncryption отнаследован от Encryption, не
>    имплементирует ничего из его методов, имеет говнометоды, в которых намешаны
>    оба вида шифрования.
>
> Если ты считаешь, что это хорошая декомпозиция классов для выполнения
> поставленной задачи, то могу посоветовать пройти курс уколов галоперидолом.
>
> Для самых маленьких и тупых пишу как должно быть, чтобы не нарушалась
> половина SOLID-принципов:
>
>    - класс Encryption абстрактный, объявляет два метода - decrypt, encrypt,
>    generate_key.
>    - класс SymmetricEncryption отнаследован от Encryption, имплементирует
>    методы decrypt, encrypt, generate_key для 3DES.
>    - класс AsymmetricEncryption отнаследован от Encryption,
>    имплементирует методы decrypt, encrypt, generate_key для RSA.
>    - класс HybridCryptosystem имеет в качестве атрибутов экземпляр
>    SymmetricEncryption и AsymmetricEncryption и имеет методы для
>    выполнения режимов работы, заявленных в условии лабораторной.
>
> —
> Reply to this email [...]

2023-06-03 11:55 UTC, alxmcs approved these changes

2023-06-03 13:17 UTC, closed without merging