Гусарова Маргарита Олеговна 6211-100503D Основы информационной безопасности. 2 курс. Лабораторная №3
itsecd/isb-3 pull request #30
Opened 2023-05-16 19:21 UTC by MaargoGysarova

выполнила 3 лабораторную работу "Построение гибридной криптосистемы", которая состояла из:

Генерация ключей гибридной системы:
1.1. Сгенерировать ключ для симметричного алгоритма.
1.2. Сгенерировать ключи для ассиметричного алгоритма.
1.3. Сереализовать ассиметричные ключи.
1.4. Зашифровать ключ симметричного шифрования открытым ключом и сохранить по указанному пути.

Шифрование данных гибридной системой:
2.1. Расшифровать симметричный ключ.
2.2. Зашифровать текст симметричным алгоритмом и сохранить по указанному пути.

Дешифрование данных гибридной системой:
3.1. Расшифровать симметричный ключ.
3.2. Расшифровать текст симметричным алгоритмом и сохранить по указанному пути.

2023-05-17 09:48 UTC, alxmcs requested changes

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +import os
Оптимизировать импорты

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # строка для ввода текста и кнопка для его сохранения в переменную
Комментарии вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # показать строку для ввода текста и кнопку для сохранения введенного текста
Комментарии вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # сохранение введенного текста в переменную
Комментарии вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # классы для генерации ключей и их сериализации
Комментарии вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # сохранение ключей в файлы
Комментарии вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        # print(self.text)
Закомменченный код убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +    # сериализация приватного ключа в формате PEM
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +    # десериализация открытого ключа
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +    def get_public_key(self) -> bytes:
Нет докстринга

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +        # расшифровка симметричного ключа
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +        # чтение файла
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +        # шифрование текста
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +        # расшифровка симметричного ключа
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +        # чтение файла
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +    # Зашифровать ключ симметричного шифрования открытым ключом и сохранить по указанному пути.
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +    # Расшифровать ключ симметричного шифрования закрытым ключом и сохранить по указанному пути.
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on symmetrical_encrpt.py
> +    # сериализация симметричного ключа
Комменты вне докстрингов убрать

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +            logging.error(f"error in file")
1) бесполезный f-стринг
2) нет вывода системного сообщения об ошибке

2023-05-17 09:48 UTC, alxmcs commented on asymmetric_encrpt.py
> +            logging.error(f"error in file")
1) бесполезный f-стринг
2) нет вывода системного сообщения об ошибке

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print(text)
Заменить на `logging`

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print('button 2')
Заменить на `logging`

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print('button 3')
Заменить на `logging`

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print('button 1')
Заменить на `logging`

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print(self.count)
Заменить на `logging`

2023-05-17 09:48 UTC, alxmcs commented on Window.py
> +        print(self.count)
Заменить на `logging`

2023-05-20 16:48 UTC, MaargoGysarova commented on Explanation.txt
> +Пока ключи не будут сгенерированы, пользователь не сможет расшифровать и расшифровать файл - кнопки не доступны и пользователя об этом уведомляют.
Все недочеты поправила. Теперь у пользователя есть возможность считать ключи из выбранного им файла 😃

2023-05-23 07:44 UTC, alxmcs requested changes
В коде все еще остались print-ы вместо logging.
Часть логируемых сообщений все еще помечены как f-стринги, хотя никакой интерполяции переменных в них не происходит

2023-05-23 14:26 UTC, alxmcs requested changes
Те комментарии, которые остались не outdated с предыдущего ревью тебе все равно придется исправить рано или поздно.

Видимо, ты выбираешь поздно.

2023-05-23 14:29 UTC, MaargoGysarova commented
> Те комментарии, которые остались не outdated с предыдущего ревью тебе все равно придется исправить рано или поздно.
> 
> Видимо, ты выбираешь поздно.

Так я же добивала docstring , добавила logging.info и loggong.error и убрала комментарии вне docstring

2023-05-23 14:31 UTC, alxmcs commented
Но это не все

2023-05-23 14:47 UTC, MaargoGysarova commented on symmetrical_encrpt.py
> +    def serialization_symmetric_key(self):
Добавлен

2023-05-23 14:49 UTC, MaargoGysarova commented
> Но это не все

А что еще ? Я просто уже запуталась в поправках. Не пойму, что еще не outdated

2023-05-24 06:52 UTC, alxmcs approved these changes

2023-05-30 06:20 UTC, closed without merging