6211 Маясов Данила Вячеславович Вариант 3
itsecd/isb-3 pull request #31
Opened 2023-05-19 10:42 UTC by danyala1

В данной лабораторной работе была написана гибридная криптосистема.

2023-05-19 14:09 UTC, alxmcs requested changes

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +        except:
Не логгируется успех выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +    def generate_keys(self) -> None:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on assymetric.py
> +    def decryption(self) -> None:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on decrypt.py
> +def decrypt_data(encrypted_file: str, private_key: str,
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on encryption.py
> +def encrypt_data(decrypted_file: str, private_key: str, symmetric_key: str, encrypted_file: str, symmetric_key_decrypted, size: int) -> None:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on keys_generate.py
> +def keys_generator(private_key: str, public_key: str, symmetric_key: str, symmetric_key_decrypted: str, size: int) -> None:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on main.py
> +def get_argument():
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on main.py
> +    except FileNotFoundError:
Нет логгирования успешного выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +        except:
Нет логгирования успешного выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +        except:
Нет логгирования успешного выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +        except:
Нет логгирования успешного выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +        except:
Нет логгирования успешного выполнения кода

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +    def generate_key(self) -> None:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +    def __padding_data(self, data: str) -> bytes:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +    def __de_padd(self, plain_text: str) -> bytes:
Нет логгирования

2023-05-19 14:09 UTC, alxmcs commented on symmetric.py
> +        except:
Нет логгирования успешного выполнения кода

2023-05-19 15:43 UTC, danyala1 commented
Исправился

2023-05-20 08:35 UTC, alxmcs approved these changes

2023-05-25 05:30 UTC, closed without merging