6212-100503 Нестеренко Андрей лаб.1 Вар №8
itsecd/isb-3 pull request #33
Opened 2023-05-20 13:01 UTC by MagGoldi

2023-05-22 13:15 UTC, alxmcs requested changes
Общие замечания:
1) Логическая декомпозиция кода - отвратительна,
2) Физической декомпозиции кода вообще нет,
3) Вменяемого логирования нет,
4) Вменяемой обработки исключений - тоже,
5) У пользователя нет возможности передать собственный файл с настройками,
6) Про РЕР ты, видимо, не слышал

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print(
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    pass
Бесполезный `pass`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    pass
Бесполезный `pass`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    pass
Бесполезный `pass`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print(f'Key: {d_key}')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print(f"Текст зашифрован и сериализован по адресу: {encrypted_f}")
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print("Расшифрованный текст:")
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print(d_text.decode('UTF-8'))
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    print(f"Текст расшифрован и сериализован по адресу:  {decrypted_file} ")
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Отсутствует файл с исходным текстом, скачивание с git')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Не найден закрытый ключ. Используйте сначала режим gen')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Не найден симметричный ключ. Используйте сначала режим gen')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Отсутствует файл с исходным текстом, скачивание с git')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Не найден закрытый ключ. Используйте сначала режим gen')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Не найден симметричный ключ. Используйте сначала режим gen')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                print('Не найден зашифрованный файл. Используйте сначала режим enc')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            print('что то не то...')
Заменить на методы `logging`

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(symmetric_k, 'rb') as key_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(secret_k, 'rb') as pem_in:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(symmetric_k, 'rb') as key:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(inital_f, 'rb') as o_text:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(vec_init, 'wb') as iv_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(encrypted_f, 'wb') as encrypt_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(secret_k, 'rb') as pem_in:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(symmetric_k, 'rb') as key:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(encrypted_f, 'rb') as e_text:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(vec_init, 'rb') as iv_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +    with open(decrypted_file, 'w', encoding='UTF-8') as decrypt_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                with open('settings.json', 'w') as fp:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            with open('settings.json', 'r') as json_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                with open('settings.json', 'w') as fp:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            with open('settings.json', 'r') as json_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +                with open('settings.json', 'w') as fp:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            with open('settings.json', 'r') as json_file:
Нет обработки исключения

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            if not os.path.exists('settings.json'):
Захардкоженный путь к файлу

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            if not os.path.exists('settings.json'):
Захардкоженный путь к файлу

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            if not os.path.exists('settings.json'):
Захардкоженный путь к файлу

2023-05-22 13:15 UTC, alxmcs commented on main.py
> +            if not os.path.exists('file.txt'):
Захардкоженный путь к файлу

2023-05-25 06:02 UTC, alxmcs requested changes
Потрясающая декомпозиция кода
![image](https://github.com/itsecd/isb-3/assets/70561974/34179f84-7298-4a2f-a90b-c9650afddb4c)
![image](https://github.com/itsecd/isb-3/assets/70561974/582eaa0e-9d3d-447e-bd31-6b267247dec9)

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            if not os.path.exists('settings.json'):
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                with open('settings.json', 'w') as fp:
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            with open('settings.json', 'r') as json_file:
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Отсутствует файл с исходным текстом, скачивание с git')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Не найден закрытый ключ. Используйте сначала режим gen')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Не найден симметричный ключ. Используйте сначала режим gen')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            if not os.path.exists('settings.json'):
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                with open('settings.json', 'w') as fp:
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            with open('settings.json', 'r') as json_file:
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            if not os.path.exists('file.txt'):
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Отсутствует файл с исходным текстом, скачивание с git')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Не найден закрытый ключ. Используйте сначала режим gen')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Не найден симметричный ключ. Используйте сначала режим gen')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +                print('Не найден зашифрованный файл. Используйте сначала режим enc')
Претензия с прошлого ревью не исправлена

2023-05-25 06:02 UTC, alxmcs commented on main.py
> +            print('что то не то...')
Претензия с прошлого ревью не исправлена

2023-05-25 06:05 UTC, alxmcs commented
Сорян, похоже я поторопился с ревью - ре-риквеста же не было

2023-05-25 06:34 UTC, MagGoldi commented
Вот теперь все. Разделил функции по файлам, добавил сохранение/загрузку файлов, исправил parser

2023-05-26 09:53 UTC, alxmcs approved these changes
Стало явно лучше

2023-05-29 11:37 UTC, closed without merging