Морозов 6212 Л.Р.3 ИНФ. БЕЗ
itsecd/isb-3 pull request #38
Opened 2023-05-22 13:14 UTC by kingtuler1454

для удобства написал гуи в одном файлике. Мой вариант АES

2023-05-22 14:42 UTC, alxmcs requested changes
После просмотра данного исходника у меня есть только две гипотезы:
1) Это сознательный акт агрессии автора кода в мою сторону, чтобы пошатнуть мое психическое благополучие,
2) Автор кода имеет повреждения коры головного мозга.

Мне совершенно не интересно, какое из этих предположений верно, меня интересует, чтобы это преступление против человечества превратилось в грамотно структурированный человекочитаемый код.

2023-05-22 14:42 UTC, alxmcs commented on encrypted_file_path/finish_text.txt
> +b'the need to encrypt and transmit encrypted messages arose a very long time ago. So, even in the ancient Greeks used a special encryption device. according to the description of the plutarch, it con
Не смущает, что дешифованный текст не совпадает с исходным?

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +
Нарушение РЕР- число пустых строк

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    # :param symmetric_key_path:  путь, по которому сериализовать зашифрованный симметричный ключ
Это не докстринг

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # :param encrypted_file_path: путь к зашифрованному текстовому файлу
Это не докстринг

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +
Нарушение РЕР- число пустых строк

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +         # 1.3 сериализация открытого ключа в файл
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        #1.4 шифрование симметричного ключа открытым ключом при помощи RSA-OAEP
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # десериализация закрытого ключа
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # дешифрование симметричного ключа асимметричным алгоритмом
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # паддинг данных для работы блочного шифра (делаем длину сообщения кратной длине шифруемого блока --------------------- (64 бита))
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # шифрование текста симметричным алгоритмом
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # зашифрованный текст хранится в виде словаря, где под ключом 'text' хранится сам зашифрованный текст,
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # десериализация ключа симметричного алгоритма
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # десериализация закрытого ключа
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # дешифрование симметричного ключа асимметричным алгоритмом
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # десериализация шифрованного файла
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +        # дешифрование и депаддинг текста симметричным алгоритмом
Комментарии вне докстринга убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def  button_first_field_click(self):
Нет докстринга, нет тайп хинта

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def  button_second_field_click(self):
Нет докстринга, нет тайп хинта

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def  button_third_field_click(self):
Нет докстринга, нет тайп хинта

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def button_fourth_field_click(self):
Нет докстринга, нет тайп хинта

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def button_OK_click(self):
Нет докстринга, нет тайп хинта

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    def  button_first_field_click(self):
`button_first_field_click`,`button_second_field_click`,`button_third_field_click`, `button_fourth_field_click` - потрясающий квартет похожих друг на друга, как славянские браться в песнях группы "Коловрат", методов. Которые можно заменить единственным, если додуматься добавить параметр.

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +    window.setStyleSheet("#MainWindow{border-image:url(phon.png)}")  # 3e753b
Комментарии вне докстрингов убрать

2023-05-22 14:42 UTC, alxmcs commented on main.py
> +class Window(QMainWindow):
Класс нарушает SRP - он и отрисовывает гуи, и сериализует/десериализует файлы, и обслуживает симметричное шифрование, и обслуживает ассиметричное шифрование.
Вместо него должно появиться как минимум 4 класса с четким разделением обязанностей и вынесенных в разные модули.

2023-05-29 13:45 UTC, alxmcs commented
пользуясь случаем, напоминаю о существовании вот этой кнопки
![image](https://github.com/itsecd/isb-3/assets/70561974/abcd391e-5425-489d-b935-e5cc378c61fa)

2023-05-29 13:50 UTC, alxmcs commented on Переделанная работа/main.py
> +    def button_field_click1(self, number: int):
Все методы с названием вида `button_field_click*` имеют параметр `number`, который внутри метода никаким образом не используется.

Более того, все они одинаковые до такой степени, что можно было бы ограничиться единственным методом, параметрами которого можно было бы сделать передаваемый в метод элемент гуи и текст

2023-05-29 13:53 UTC, alxmcs commented on Переделанная работа/main.py
> +        self.chose_task = 1
Для повышения читабельности кода в таких местах используют енамы, а не интовые значения

2023-05-29 13:58 UTC, alxmcs commented on Переделанная работа/deserialization.py
> +        """Инициализация элемента,для удобства пропишем окончания файлов"""
Для удобства кого? Пользователь не в курсе, что входные данные и  результаты работы софта будут сформированы каким-то специфическим образом, потому что ты его никак об этом не оповещаешь.
Хотя бы сооруди какую-нибудь кнопку с модальным окном, в котором будет написано, как пользоваться софтом.

2023-05-30 09:16 UTC, kingtuler1454 commented on Переделанная работа/main.py
> +    def button_field_click1(self, number: int):
исправлено

2023-05-30 09:16 UTC, kingtuler1454 commented on Переделанная работа/main.py
> +        self.chose_task = 1
исправлено

2023-05-30 09:17 UTC, kingtuler1454 commented on Переделанная работа/deserialization.py
> +        """Инициализация элемента,для удобства пропишем окончания файлов"""
сделал инструкцию для пользователя. При входе в задачу там поясняется где какой файл будет создан

2023-05-30 11:43 UTC, alxmcs requested changes
Название директории "Переделанная работа" своим существованием намекает на проблемы с качеством кода, который в ней находится. Ты не рассматривал идею назвать эту директорию иначе?

2023-05-30 11:43 UTC, alxmcs commented on Переделанная работа/main.py
> +        self.chose_task = 1
Что исправлено? Ты енам завел и в коде его не используешь никак

2023-05-30 11:43 UTC, alxmcs commented on Переделанная работа/main.py
> +            if self.chose_task == chose_task.first_task.value:
Это говнополе должно иметь тип твоего енама, а не жрать его интовые значения.
Какой смысл было тогда енам вообще заводить, если код все еще выглядит так 
```py
if self.chose_task != 1:
```
а не так 
```py
if self.chose_task != TaskType.generate_keys:
```

2023-05-30 11:43 UTC, alxmcs commented on Переделанная работа/chose_task.py
> +    first_task = 1
Отличные именования членов перечисления. Прямо все сразу прозрачно в коде стало. :+1:

2023-05-30 11:43 UTC, alxmcs commented on Переделанная работа/chose_task.py
> +class chose_task(Enum):
Именование класса нарушает РЕР.
А еще совпадает с именем поля этого типа в классе с гуями.

2023-05-30 15:52 UTC, kingtuler1454 commented
переделал.

2023-05-31 07:12 UTC, alxmcs approved these changes
Думаю, в текущем виде код уже можно принять

2023-06-03 13:17 UTC, alxmcs commented
Зачтено

2023-06-03 13:17 UTC, closed without merging