6212 Пахомов Л. А. Лаб.3 Вар.4
itsecd/isb-3 pull request #39
Opened 2023-05-23 18:59 UTC by Sonya-From-IBAS

Написал программу для работы с гибридной криптосистемой.
В scripts/menu.py реализовано "взаимодействие" с пользователем с помощью argparse. 
Предлагается выбрать три действия:
-gen -создать ключи шифрования(симметричного и асимметричного). Симметричный ключ шифруется асимметричным шифрованием, что отбирает возможность у кого-либо(кроме владельца secret ключа) расшифровать сим. ключ.
-enc- текст из files/initialFile.txt шифруется с помощью алгоритма симметричного шифрования TripleDES.(encryptedFile.txt)
-dec - зашифрованный ранее код расшифровывается. (decryptedFile.txt)
Создал 2 класса для удобной работы с симметричным и асимметричным алгоритмами шифрования, а так же для работы с txt файлами

2023-05-24 07:14 UTC, alxmcs requested changes

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +        with open ("./files/iv.txt", "wb") as file:
И тут, соответственно, тоже

2023-05-24 07:14 UTC, alxmcs commented on scripts/asymmetric.py
> +    def secretKeyDeserialization(self, fileName: str) -> None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/asymmetric.py
> +        decryptedSymmetricKey = self.__secretKey.decrypt(symmetricKey,padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),algorithm=hashes.SHA256(),label=None))
Имя переменной нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def generateSymmericKey(self, keyLenght: int = 128)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def getKey(self)->bytes:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def setKey(self, key: bytes)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def setLen(self, len: int)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def keyDeserialization(self, fileName: str)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/symmetric.py
> +    def keySerialization(self, fileName:str)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/text.py
> +    def getText(self)->bytes:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/text.py
> +    def setText(self, text:bytes)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/text.py
> +    def textSerialization(self, fileName:str)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/text.py
> +    def textDeserialization(self, fileName:str)->None:
Имя метода нарушает РЕР

2023-05-24 07:14 UTC, alxmcs commented on scripts/text.py
> +    def getText(self)->bytes:
Геттеры и сеттеры лучше реализовывать через @property

2023-05-24 07:14 UTC, alxmcs commented on scripts/menu.py
> +    elif args.encryption is not None:
Полотно кода под этим условием вынести в отдельную функцию/метод

2023-05-24 07:14 UTC, alxmcs commented on scripts/menu.py
> +    elif args.decryption:
Полотно кода под этим условием вынести в отдельную функцию/метод

2023-05-24 07:14 UTC, alxmcs commented on scripts/menu.py
> +    if args.generation is not None:
Полотно кода под этим условием вынести в отдельную функцию/метод

2023-05-24 14:21 UTC, Sonya-From-IBAS commented
Исправил.

2023-05-25 06:06 UTC, alxmcs commented
В следующий раз рекомендую нажать на эту кнопку
![image](https://github.com/itsecd/isb-3/assets/70561974/c836c352-d65a-4a96-8d9d-45d40a00beed)

2023-05-25 06:12 UTC, alxmcs requested changes

2023-05-25 06:12 UTC, alxmcs commented on scripts/menu.py
> +        print(settings)
Это убрать

2023-05-25 06:12 UTC, alxmcs commented on scripts/menu.py
> +    # settings["keyLen"] = int(args.len)
И этот закомменченный кусок кода тоже убрать

2023-05-25 06:12 UTC, alxmcs commented on scripts/symmetric.py
> +    def get_key(self)->bytes:
Мне кажется, так все-таки удобнее
```py
   @property
    def key(self):
        return self.__key

    @key.setter
    def key(self, value):
        self.__key=value
```

2023-05-25 13:49 UTC, alxmcs approved these changes

2023-06-03 13:17 UTC, alxmcs commented
Зачтено

2023-06-03 13:17 UTC, closed without merging