Замотохина Мария 6211 Вар. 5 Лаб. 3
itsecd/isb-3 pull request #4
Opened 2023-04-23 09:58 UTC by ZamotohinaMaria

Весь код лежит в файле OIB-laba-3.py (НЕ ФАЙЛ НОУТБУКА).

В данной лабораторной работе было осуществлено шифрование и дешифрование текста с помощью алгоритма CAST5. Ключи для алгоритма шифруются ассиметричным алгоритмом. 

Для удобства работы был создан графический интерфейс простого окна, все кнопочки работают, зашифрованный и дешифрованный текст шифруются

2023-04-23 10:24 UTC, ZamotohinaMaria commented
код отформатирован по pep8, если не видно - заново создам пулл реквест

2023-04-24 09:32 UTC, alxmcs requested changes
Некоторое саммари по замечаниям:
* Есть небольшая проблема с реализацией криптографической части,
* Есть беда с srp и декомпозицией кода,
* Интерфейс во многом спроектирован для того, чтобы наносить моральные увечья пользователям софта.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def gen_keys(self):
То, что класс, отвечающий за отрисовку графического интерфейса еще и занимается симметричным и асимметричным шифрованием - нарушение SRP, и людей, которые это допускают, по моему мнению, нужно подвергать уголовному преследованию.

Соответственно, все методы, касающиеся шифрования, должны быть убраны из этого класса и этого модуля.
> под [модулем](https://docs.python.org/3/tutorial/modules.html#:~:text=A%20module%20is%20a%20file,global%20variable%20__name__%20.) здесь подразумевается скрипт, файл с расширением `.py`. Может быть, это объяснение излишне, но в процессе ревью твоих однокурсников, я выяснил, что некоторым этот термин не очевиден. Если излишне, то прошу прощения.

Соответственно, поместить их нужно в отдельный класс с репрезентативным названием, который обитал бы в отдельном модуле.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +            with open(self.file_settings['private_key'], 'wb') as private_out:
Как и здесь.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +            with open(self.file_settings['encrypted_file'], 'wb') as file:
Как и здесь.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +            with open(self.file_settings['encrypted_file'], 'rb') as file:
Как и здесь.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +            with open(self.file_settings['decrypted_file'], 'wb') as file:
Как и здесь.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    # объект приложение, должен быть всегда, принимает на вход аргументы
Этот комментарий содержит достаточно очевидную информацию. Думаю, от него можно избавиться без особенных потерь информативности.

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +        self.flag = 0
Что в себе несет этот атрибут достаточно неочевидно (отчасти от того, что никаких докстрингов в коде нет).
Его область значений в коде меняется от 0 до 2.
Чтобы повысить читаемость кода, я бы настоятельно рекомендовал использовать в качестве значений этого атрибута не целые числа, а [enum](https://docs.python.org/3/library/enum.html)

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +        self.resize(1800, 1000)
![image](https://user-images.githubusercontent.com/70561974/233942752-199f1b12-9522-4d91-894b-bcf1e77895e2.png)
Это действительно в твоем понимании оптимально подобранный лейаут приложения?

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def initUI(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def center(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def print_info_message(self, text):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def print_info_text(self, text):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def gen_keys(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def sym_key_decryption(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def text_encryption(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    def text_decryption(self):
Нет докстрингов, нет тайпхинтов

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    QHBoxLayout,
Неиспользуемый импорт

2023-04-24 09:32 UTC, alxmcs commented on OIB-laba-3.py
> +    QVBoxLayout)
Неиспользуемый импорт

2023-04-28 09:22 UTC, alxmcs commented
Если все необходимые изменения внесены, то ![image](https://user-images.githubusercontent.com/70561974/235109248-31163cc3-5d0a-4887-8195-769a2ff088fd.png)

2023-04-28 17:51 UTC, ZamotohinaMaria commented
Добрый вечер, изменения внесла по максимуму, загвостка только с выбором файлов(в коде это есть в форме закомменченого кода не ругайтесь): выбор деррктории для сохранения реализовала, но выбор конкретного файла для работы не получилось реализовать - через функцию QFileDialog.getOpenFileName получить путь к файлу не удается, прошу помощи с этим моментом.

Также оставила интерфейс окошка приложения (больно удалять все, что сделала, в следующий аз придумаю что-то более гуманное для пользователя)

2023-04-29 04:51 UTC, alxmcs requested changes
Стало гораздо лучше.
Общее замечание - я бы поместил файлы данных и файлы исходного кода в разные директории в репозитории.

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        """функция инициаизации
>инициаизации

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +class encryptor():
Название класса нарушает РЕР

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        # self.init_text = str(QFileDialog.getOpenFileName(self, 'Select file for encrypt', '*.txt'))
Закомменченный код убрать

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        self.way = os.path.abspath('')
Не помню, указывал ли я это в прошлом ревью, но привязывать путь к файлу с параметрами к пути исполняемых файлов - не очень хорошая затея.
Тем более, что передать в инициализатор путь к директории, где хранятся данные, не сложно.

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['public_key'], 'wb') as public_out:
Нет обработки исключений - файла может не быть, привилегий для его чтения/записи может не быть

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['private_key'], 'wb') as private_out:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['symmetric_key'], 'wb') as key_file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['encrypted_vector'], 'wb') as enc_vec:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['private_key'], 'rb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['symmetric_key'], 'rb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['initial_file'], 'r', encoding='UTF-8') as file:
Нет обработки исключений - файл может и существует, только может быть, например, занят другим процессом

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['encrypted_vector'], 'rb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['encrypted_file'], 'wb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['encrypted_file'], 'rb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +            with open(self.file_settings['encrypted_vector'], 'rb') as file:
Нет обработки исключений

2023-04-29 04:51 UTC, alxmcs commented on class_encryptor.py
> +        with open(self.file_settings['decrypted_file'], 'w') as file:
Нет обработки исключений

2023-04-30 11:34 UTC, ZamotohinaMaria commented
Все изменения внесены: исправлены опечатки и убран закомменченый код, добавлена возможность выбора файла для шифрования и папки для сохранения файлов. Обработаны исключения при чтении/записи в файл, добавлено логирование

2023-04-30 14:12 UTC, alxmcs approved these changes

2023-05-02 05:22 UTC, closed without merging