6214-100503D Рыжова А.А. Лаб.3 Вар.5
itsecd/isb-3 pull request #41
Opened 2023-05-26 12:35 UTC by ryzalena

Написать программу для гибридной криптосистемы. Использован CAST5.

2023-05-28 14:01 UTC, alxmcs requested changes
Общее замечание - было бы неплохо добавить пример результатов работы твоего кода в репозиторий. В отдельной директории, чтобы данные и код не лежали вместе (как происходит сейчас)

2023-06-04 22:23 UTC, ryzalena commented on class_display.py
> +        if (flag == 0):
match/case поддерживается версией питона 3.10+, мой виндовс 7 поддерживает только версию питона 3.8

2023-06-04 22:32 UTC, ryzalena commented on class_display.py
> +                'Ошибка: Невозможно открыть файл с вектором шифрования')
Это инициализационный вектор

2023-06-12 07:46 UTC, ryzalena commented
Необходимые изменения внесены

2023-06-12 09:16 UTC, alxmcs commented
В таком случае ![image](https://github.com/itsecd/isb-3/assets/70561974/97396b4f-e49f-4cff-9750-d1b628984cd1)

2023-06-12 10:41 UTC, alxmcs requested changes

2023-06-12 10:41 UTC, alxmcs commented on class_display.py
> +                'Ошибка: Невозможно открыть файл с вектором шифрования')
Тогда как насчет так его и назвать?

2023-06-12 10:41 UTC, alxmcs commented on class_encoder.py
> +class Encoder():
В данный момент класс состоит толькео из инициализатора экземпляра, в который запиханы qt-шные файл диалоги. Это явно неудачная декомпозиция

2023-06-12 10:41 UTC, alxmcs commented on class_receiving.py
> +class Receiving():
Вместо текущего сомнительного набора классов я бы предложил выделить в отдельные сущности  функционал по работе с ассиметричной криптографией (шифрование, дешифрование, генерацию ключей), с симметричной криптографией (шифрование, дешифрование, генерацию ключа) и класс для выполнения непосредственно сценариев работы из задания лабораторной, который бы использовал для этих нужд экземпляры описанных выше классов

2023-06-13 06:05 UTC, alxmcs commented
Нет желания поводить код до приемлемого состояния - заставлять не буду.
Семестр подошел к концу, лабораторная не засчитана.

2023-09-21 06:13 UTC, alxmcs commented
С прошлого семестра осталось провести рефакторинг

2023-09-21 10:17 UTC, alxmcs commented
Если этого по твоему мнению достаточно, то ![image](https://github.com/itsecd/isb-3/assets/70561974/36df6213-d76d-4bf9-8d15-3f2c32e80ae4)

2023-09-25 07:58 UTC, alxmcs requested changes

2023-09-25 07:58 UTC, alxmcs commented on class_encoder.py
> +        self.way_to_init_text = str(QFileDialog.getOpenFileName(caption='Выберите файл для шифровки', filter='*.txt'))
Вызов кода библиотеки графического интерфейса в инициализаторе класса с бизнес логикой приложения все еще на месте. Его там не должно быть.
Хочешь в качестве параметра иметь путь к файлам - ради бога, передай его как строковый параметр в инициализатор. Не надо вызов библитеки с инфраструктурного слоя приложения пихать в слой домена.

2023-09-25 07:58 UTC, alxmcs commented on class_encoder.py
> +        self.way = str(QFileDialog.getExistingDirectory(caption='Выберите папку для сохранения'))
Аналогично

2023-09-25 13:01 UTC, alxmcs requested changes

2023-09-25 13:01 UTC, alxmcs commented on class_encoder.py
> +        self.way_to_init_text = "isb-3\initial_file.txt"
Фраза "передать в качестве строкового параметра" предполагала, что в качестве аргумента в инициализаторе помимо `self` появится нечто вроде `initial_file_path : str`, а не захардкоженная строчка

2023-09-25 13:01 UTC, alxmcs commented on class_encoder.py
> +        self.way ="isb-3\files"
Аналогично

2023-09-26 06:52 UTC, alxmcs requested changes
К сожалению, иногда я действительно смотрю код, который приходит ко мне на ревью. И этот код в текущем нерабочем состоянии принимать не планирую.

2023-09-26 06:52 UTC, alxmcs commented on class_encoder.py
> +            way_to_files = "isb-3\files",
Ты пытаешься хотя бы запускать код перед тем как запрашивать ревью? Ничего не смущает тебя в этом фрагменте кода?

2023-09-26 06:52 UTC, alxmcs commented on class_encoder.py
> +
Многовато пустых строк

2023-09-26 06:52 UTC, alxmcs commented on class_encoder.py
> +class Encoder():
В данный момент в коде экземпляр этого чудо-класса инициализируется на 25 строке в class_display.py и больше  никак не используется. Соответственно, возникает вопрос - какого черта он существует?

2023-09-26 06:52 UTC, alxmcs commented on class_encoder.py
> +from PyQt5.QtWidgets import QFileDialog
Неиспользуемый импорт

2023-09-26 06:52 UTC, alxmcs commented on class_encoder.py
> +class Flag(Enum):
Прекрасный enum, который также нигде в коде не используется, кроме как в классе, который тоже нигде в коде не используется

2023-09-26 10:35 UTC, alxmcs approved these changes
Декомпозиция текущей версии кода нарушает SOLID, ux приложения - пытка пользователя, однако, это, наконец-то, создает отдаленное впечатление рабочего сотфа.

Тщательно копаться в этом мне надоело.

2023-09-26 10:35 UTC, closed without merging