Основы информационной безопасности. 2 курс. Лабораторная №3. 2 вариант. Карпачева Полина 6212-100503D
itsecd/isb-3 pull request #42
Opened 2023-05-26 16:31 UTC by PolinaKrp

В лабораторной работе был использован алгоритм симметричного шифрования Camellia.

Camellia — совместная разработка NTT и еще одной японской компании Mitsubishi Electric — стал одним из победителей (в номинации 128-битных алгоритмов блочного симметричного шифрования) европейского конкурса криптоалгоритмов NESSIE. Сертифицирован японской организацией CRYPTREC как рекомендованный для промышленного и государственного использования алгоритм.

Camellia является дальнейшим развитием алгоритма шифрования E2, одного из алгоритмов, представленных на конкурсе AES и с использованием элементов алгоритма MISTY1.

2023-05-28 14:03 UTC, alxmcs commented
![image](https://github.com/itsecd/isb-3/assets/70561974/b77bf721-5a39-461e-af35-525f4c0341e4)
Это может показаться неочевидным, однако я в курсе, какой предмет я веду и какая это лабораторная по счету.
Единственное, о чем я не в курсе - это кто пытается сдать этот код, потому что ФИО и номера группы в заголовке пул-риквеста я не наблюдаю.

2023-05-28 14:04 UTC, alxmcs commented on main.py
> +settings = {
Нарушение РЕР при именовании константы

2023-05-28 14:06 UTC, alxmcs commented on main.py
> +if args.generation is not None:
Синтаксис этого условия излишний

2023-05-28 14:06 UTC, alxmcs commented on main.py
> +if args.encryption is not None:
Аналогично

2023-05-28 14:06 UTC, alxmcs commented on main.py
> +if args.decryption is not None:
Аналогично

2023-05-28 14:08 UTC, alxmcs commented on main.py
> +def input_len_key() -> int:
Я неоднократно говорил, что получать параметры для работы софта через инпуты запрещено. Более того, у тебя в коде уже фигурирует argparse. Так настрой аргумент командной строки для нужд получения длины ключа шифрования.

Или десериализуй длину ключа из жсона с настройками

2023-05-28 14:09 UTC, alxmcs commented on main.py
> +    klen = input()
Именование пременной нарушает РЕР

2023-05-28 14:11 UTC, PolinaKrp commented
Извините, забыла написать. Карпачева Полина. 6212-100503D

2023-05-28 14:12 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='main.py')
Код с точкой входа в приложение не убран под if __name__ == "__main__"

2023-05-28 14:13 UTC, alxmcs commented on main.py
> +with open('settings.json') as json_file:
В качестве аргумента командной строки приложение должно получить путь к файлу с настройками, чтобы путь к нему не был захардкожен

2023-05-28 14:13 UTC, alxmcs commented on main.py
> +def generate_key(encrypted_symmetric_key: str, public_key_path: str, secret_key_path: str, len_key: int) -> None:
Нет докстринга

2023-05-28 14:14 UTC, alxmcs commented on main.py
> +    print('Key length: ' + str(len_key))
Заменить на logging

2023-05-28 14:14 UTC, alxmcs commented on main.py
> +        print('\n Encryption successful.\n')
Заменить на logging

2023-05-28 14:14 UTC, alxmcs commented on main.py
> +        print('\n Decryption successful.\n')
Заменить на logging

2023-05-28 14:15 UTC, alxmcs commented on main.py
> +def generate_key(encrypted_symmetric_key: str, public_key_path: str, secret_key_path: str, len_key: int) -> None:
Эта функция должна быть декомпозирована на две - тут генерируются и сериализуются ключи для различных алгоритмов

2023-05-28 14:16 UTC, alxmcs commented on main.py
> +def encrypt_data(text_file: str, secret_key_path: str, encrypted_symmetric_key_path: str,
Эта функция также должна быть декомпозиорвана. Из нее нужно выделить код в отдельные функции, отвечающие за работу с файловыми потоками и различными алгоритмами шифрования.

2023-05-28 14:17 UTC, alxmcs commented on main.py
> +def decrypt_data(encrypted_text_file_path: str, secret_key_path: str, encrypted_symmetric_key_path: str,
Аналогично - тут намешано симметричное шифрование, ассиметричное шифрование, десериализация ключей и работа с файловыми потоками. Все это должно быть вынесено в отдельные функции.

2023-05-28 14:18 UTC, alxmcs commented on main.py
> +    with open(public_key_path, 'wb') as public_out:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:18 UTC, alxmcs commented on main.py
> +    with open(secret_key_path, 'wb') as private_out:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:18 UTC, alxmcs commented on main.py
> +    encrypt_symmetrical_key = public_key.encrypt(symmetrical_key.key,
Нет обработки исключений при открытии файлового потока

2023-05-28 14:18 UTC, alxmcs commented on main.py
> +    with open(encrypted_symmetric_key, 'wb') as summetric_out:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:19 UTC, alxmcs commented on main.py
> +    with open(encrypted_symmetric_key_path, "rb") as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:19 UTC, alxmcs commented on main.py
> +    with open(secret_key_path, 'rb') as pem_in:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:19 UTC, alxmcs commented on main.py
> +    with open(text_file, "r", encoding='UTF-8') as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:19 UTC, alxmcs commented on main.py
> +    with open(encrypted_text_file_path, "wb") as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:19 UTC, alxmcs commented on main.py
> +    with open(encrypted_symmetric_key_path, "rb") as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:20 UTC, alxmcs commented on main.py
> +    with open(secret_key_path, 'rb') as pem_in:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:20 UTC, alxmcs commented on main.py
> +    with open(encrypted_text_file_path, 'rb') as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:20 UTC, alxmcs commented on main.py
> +    with open(decrypted_text_file_path, 'w', encoding='UTF-8') as file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:20 UTC, alxmcs commented on main.py
> +with open('settings.json') as json_file:
Нет обработки исключений при открытии файлового потока

2023-05-28 14:21 UTC, alxmcs commented on main.py
> +        progressbar.update(100)
У тебя прогресс бар апдейтится с нуля до сотни единственный раз. Ты правда считаешь, что это хороший способ продемонстрировать пользователю прогресс работы твоего софта?

2023-05-28 14:21 UTC, alxmcs commented on main.py
> +        progressbar.update(100)
Аналогично

2023-05-28 14:28 UTC, alxmcs commented
И еще одно замечание:

Код не приму, пока не увижу коммит с локальной машины, а не через драг-н-дроп на сайте.

![image](https://github.com/itsecd/isb-3/assets/70561974/8ac1d0f5-cd61-4a64-bd8a-38facce8c17b)

2023-05-28 16:42 UTC, PolinaKrp commented
Запуталась в поправках, но вроде исправила.

2023-05-29 09:20 UTC, alxmcs requested changes
Код стал чуть лучше, только перестал работать.

Все еще не наблюдаю ни единого коммита через гит, а не через веб-интерфейс сайта

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +def input_len_key(k_len: int):
Эта функция нигде не используется. И слава богу. Но ее надо убрать из исходников.

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +            with open('settings.json') as json_file:
Вместо того, чтобы хардкодить путь к файлу с настройками, можно было бы передать путь к нему через аргумент командной строки

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +            with open('settings.json') as json_file:
Зачем открывать файл с настройками под каждым условием?

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +            with open('settings.json') as json_file:
Зачем открывать файл с настройками под каждым условием?

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +        key_length = generate_key(json_data['symmetric_key'], json_data['public_key'], json_data['secret_key'])
Этот метод возвращает None по сигнатуре. Каким образом ты планируешь достать из него key_length?

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +        key_length = generate_key(json_data['symmetric_key'], json_data['public_key'], json_data['secret_key'])
Более того, эта функция принимает 4 аргумента, а передается ей только 3

2023-05-29 09:20 UTC, alxmcs commented on script/main.py
> +SETTINGS = {
Эта константа нигде не используется

2023-05-31 07:25 UTC, alxmcs requested changes

2023-05-31 07:25 UTC, alxmcs commented on scripts/generate.py
> +    else:
В данный момент твой метод работает так:
* Если приходит правильный параметр, генерируется ключ, логируется успешная генерация, ключ возвращается.
* Если приходит неправильный параметр, логируется ошибка длины ключа, возвращается пустой ключ.

Тебя никак не смущает второй сценарий?

2023-05-31 07:25 UTC, alxmcs commented on scripts/generate.py
> +        logging.info(
Это сообщение явно не `info` уровня

2023-05-31 07:25 UTC, alxmcs commented on scripts/decrypt.py
> +def decrypt_asym_data(secret_key, text: bytes) -> bytes:
`secret_key` - мы не знаем что это такое, если бы мы знали что это такое, но мы не знаем что это такое
>нет тайпхинта

2023-05-31 08:06 UTC, PolinaKrp commented
Внесла поправки. Надеюсь, что это все...

2023-05-31 09:15 UTC, alxmcs requested changes
Это не все

2023-05-31 09:15 UTC, alxmcs commented on scripts/generate.py
>      else:
Предыдущее замечание можно перефразировать таким образом: "Рейзни тут подходящее исключение"

2023-05-31 09:35 UTC, PolinaKrp commented on scripts/generate.py
>      else:
Внесла поправки

2023-05-31 10:06 UTC, alxmcs requested changes

2023-05-31 10:06 UTC, alxmcs commented on scripts/generate.py
>      else:
Работа софта не должна продолжиться штатно, если указанная длина пользователем ключа не попадает в набор допустимых.

Я не знаю, как уже объяснить другими словами, что я от тебя хочу. Вот код, добавь его.
```py
logging.warning(' The length of the key is not in choices: {}'.format(choices))
raise ValueError(f'The length of the key {len} is not allowed')
```

2023-05-31 10:12 UTC, PolinaKrp commented on scripts/generate.py
>      else:
Добавила

2023-05-31 11:32 UTC, alxmcs requested changes

2023-05-31 11:32 UTC, alxmcs commented on scripts/generate.py
> -    return key
А return зачем удалила?
>хватит издеваться над стариком

2023-05-31 11:49 UTC, alxmcs approved these changes
🎉

2023-05-31 11:49 UTC, PolinaKrp commented on scripts/generate.py
> -    return key
Извините, случайно вышло, не заметила.

2023-06-13 08:06 UTC, closed without merging