Миронюк Матвей Марсович 6212
itsecd/isb-3 pull request #43
Opened 2023-05-26 17:35 UTC by Matvey6M6

В данной лабораторной работе приведена гибридная криптосистема которая работает с симметричными и ассиметричеными алгоритмами шифрования. В данной лабораторной работе я использовал алгоритм симметричного блочного шифрования - Camellia (размер блока 128 бит, ключ 128, 192, 256 бит)

2023-05-28 14:41 UTC, alxmcs requested changes
Код из модулей decryption.py, encryption.py и keys_generator.py объединить под единым классом.

И бесовщину в main.py на 40-42 исправить

2023-05-28 14:41 UTC, alxmcs commented on assymetric.py
> +logging.basicConfig(level=logging.INFO)
Нарушение РЕР - число пустых строк

2023-05-28 14:41 UTC, alxmcs commented on main.py
> +    settings = str()
Это че

2023-05-28 14:41 UTC, alxmcs commented on main.py
> +        logging.error(f"Не найден json файл")
Нет вывода системной информации об исключении

2023-05-28 14:41 UTC, alxmcs commented on main.py
> +            logging.error("Отмена шифрования данных")
Нет вывода системной информации об исключении

2023-05-28 14:41 UTC, alxmcs commented on main.py
> +            logging.error("Ошибка при дешифрации")
Нет вывода системной информации об исключении

2023-05-28 14:41 UTC, alxmcs commented on main.py
> +        logging.error("Режим прогроммы не выбран")
Нет вывода системной информации об исключении

2023-05-28 17:18 UTC, Matvey6M6 commented on main.py
> +        logging.error("Режим прогроммы не выбран")
вы хотите чтобы конкретная ошибка показывалась, как я понял 
но у меня в других модуля присутствует логирование и если, что то идет не, то логи сообщают о конкретной ошибке.
а это логгирование, скажем так, общее, что режим не отработал корректно, а что именно отработало не так пишется выше.

2023-05-28 17:18 UTC, Matvey6M6 commented
исправил

2023-05-29 09:26 UTC, alxmcs requested changes

2023-05-29 09:26 UTC, alxmcs commented on main.py
> +        logging.error(f"Не найден json файл")
Ну тогда тут надо убрать бесполезный f-стринг, потому что никакой интерполяции строк тут нет

2023-05-29 09:26 UTC, alxmcs commented on main.py
> +            logging("НЕ получилось сгенерировать ключи ")
Чего-то не хватает

2023-05-29 09:26 UTC, alxmcs commented on main.py
> +        logging.error("Режим прогроммы не выбран")
>прогроммы

2023-05-29 09:26 UTC, alxmcs commented on main.py
> +            logging.info('Данные зашифрованный')
>Данные зашифрованный

All your base are belong to us

2023-05-29 15:13 UTC, Matosik commented on main.py
> +            logging.info('Данные зашифрованный')
![image](https://github.com/itsecd/isb-3/assets/113327388/66c89d77-c8c3-43b4-a2ef-43362dcc5f35)

2023-05-29 17:19 UTC, Matvey6M6 commented
вроде всё

2023-05-30 06:29 UTC, alxmcs approved these changes

2023-06-03 13:17 UTC, alxmcs commented
Зачтено

2023-06-03 13:17 UTC, closed without merging