Карпов Владимир 6212-1000503D
itsecd/isb-3 pull request #45
Opened 2023-05-28 17:10 UTC by Vouchiko

2023-05-29 05:58 UTC, Vouchiko commented
В данной лабораторной работе был использован алгоритм симметричного шифрования ChaCha20

2023-05-29 09:51 UTC, alxmcs requested changes
Общее замечание:
Файлы в репозитории навалены совершенно хаотично. Я хочу увидеть код в одной директории, а данные  - в другой.
![image](https://github.com/itsecd/isb-3/assets/70561974/ea87df6f-58e8-4568-8639-60385893c67b)

2023-05-29 09:51 UTC, alxmcs commented on crypt.txt
> +Задание
Если тебе действительно хочется описать какую-то инструкцию по своему софту, то оформи ее в качестве ридми к репозиторию.
И с разметкой, а не с плейн текстом

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +parser.add_argument('mode', type=str, help='1 to encrypt or 2 to decrypt')
Где генерация ключей?

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f1 = open("keys/key.txt", "rb")
Файловый поток не закрыт по окончанию действий.
Либо используй `with`, либо `close()`. Предпочтительнее `with`.

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f2 = open("keys/nonce.txt", "rb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f3 = open("encrypt_text.txt", "wb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f4 = open("crypted_sym_key.txt", "wb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f5 = open("crypted_sym_nonce.txt", "wb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f4 = open(args.encrypt_sym_key, "rb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f5 = open(args.encrypt_sym_nonce, "rb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f6 = open("encrypt_text.txt", "rb")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        f7 = open("decrypt_text.txt", "w")
Аналогично

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +    print('Encryption of data')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print('Key Serialization...')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print('Serialization of an additional parameter...')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print('Data encryption...')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print('Complete!')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print("Wrong file name")
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print("File not found")
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +    print('Decryption of data...')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print('Complete!')
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print("Some file is damaged")
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print("Please recreate the keys")
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +        print ("Something wrong with file names. Check it out")
Заменить на методы `logging`

2023-05-29 09:51 UTC, alxmcs commented on decryption.py
> +class Decrypt:
Нет докстринга

2023-05-29 09:51 UTC, alxmcs commented on decryption.py
> +    def un_padding_t(self, dc_text):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on decryption.py
> +    def simmetric_decryptor(self, text, key, inizializer, nonc):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on decryption.py
> +    def public_deserialization(self, public_pem):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on encryption.py
> +class Encrypt:
Нет докстринга

2023-05-29 09:51 UTC, alxmcs commented on encryption.py
> +    def public_serialization(self, public_key):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on encryption.py
> +    def private_serialization(self, private_key):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on encryption.py
> +    def rsa_encryption(self, text, public_key):
Нет докстринга, нет тайпхинтов, нет логгирования выполнения

2023-05-29 09:51 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='encrypter')
В целом, не самый удачный выбор аргументов для софта

2023-05-29 10:40 UTC, Vouchiko commented on crypt.txt
> +Задание
Это не описание инструкции. На самом деле это просто текст который используется для шифрования и его последующего дешифрования, который я взял с файла ISB_Lab3.ipynb

2023-05-31 09:22 UTC, alxmcs requested changes

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +parser = argparse.ArgumentParser(description='encrypter')
Убрать под `if __name__ == "__main__":`

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +        with open("Data/Encryption/crypted_sym_key.txt", "wb") as f4:
Захардкоженный путь к файлу

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +        with open("Data/Encryption/encrypt_text.txt", "wb") as f3:
Захардкоженный путь к файлу

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +        with open("Data/keys/key.txt", "rb") as f1, open("Data/keys/nonce.txt", "rb") as f2:
Захардкоженный путь к файлу

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +    enc.key_serialization("Data/keys/key.txt", k)
Захардкоженный путь к файлу

2023-05-31 09:22 UTC, alxmcs commented on main.py
> +    enc.key_serialization("Data/keys/nonce.txt", n)
Захардкоженный путь к файлу

2023-06-02 05:15 UTC, alxmcs approved these changes

2023-06-03 13:17 UTC, alxmcs commented
Зачтено

2023-06-03 13:17 UTC, closed without merging