6212 Якушева Елена Дмитриевна Лаб.3 Вар. 1
itsecd/isb-3 pull request #59
Opened 2023-06-12 20:26 UTC by lenayak

В данной лабораторной работе :
    Генерация ключей гибридной системы
    Шифрование данных гибридной системой
    Дешифрование данных гибридной системой

В качестве алгоритма симметричного шифрования использован AES

2023-06-13 06:03 UTC, alxmcs requested changes
В течение семестра было достаточно времени сделать работу. Пул-риквест, сделанный в ночь перед неофициальным дополнительным занятием, я смотреть уже не буду.

2023-09-21 05:38 UTC, alxmcs requested changes

2023-09-21 05:38 UTC, alxmcs commented on decryption.py
> +from cryptography.hazmat.primitives import padding as symmetric_padding
Стоит декомпозировать код - перекомпоновать функции из `encpyption.py` и `decryption.py` по трем модулям:
* модуль с ассиметричной криптографией
* модуль с симметричной криптографией
* модуль с функциями гибридной криптосистемы

Это повысит читаемость кода и позволит избежать необходимости, например, вешать алиасы на разные методы паддинга. К тому же, если кому-то потребуется импортировать код твоего проекта в свой ради только симметричной (или только ассиметричной) криптографии, ему будет достаточно импорта только одного модуля, а не всего кода проекта.

2023-09-21 05:38 UTC, alxmcs commented on generation_keys.py
> +            "Invalid key length: the key length should be 128/192/256 in 8-bit increments")
Для лога было бы неплохо указать, какая длина ключа была подана в функцию

2023-09-21 05:38 UTC, alxmcs commented on generation_keys.py
> +            "Symmetric and asymmetric keys generated and written to a file")
И тут тоже

2023-09-21 05:38 UTC, alxmcs commented on generation_keys.py
> +            "Invalid key length: the key length should be 128/192/256 in 8-bit increments")
Никакого 8 битного инкремента в АES нет, только три возможных значения длины ключа

2023-09-21 05:38 UTC, alxmcs commented on main.py
> +    parser.add_argument("-gen", "--generation", type = int, help="Запускает режим генерации ключей")
Добавить эти аргументы в mutual exclusive group

2023-09-21 05:38 UTC, alxmcs commented on load_info.py
> +def settings(file: str) -> dict:
Не самое грамотное название для функции. Обычно они называются словосочетанием с инфинитивной формой глагола, описывающим их назначение

2023-09-21 05:38 UTC, alxmcs commented on main.py
> +                "Invalid key length: the key length should be from 40 to 128 in 8-bit increments."
Эту строку ты не исправила в коде 5 варианта этой лабораторной, который ты взяла за основу

2023-09-21 05:38 UTC, alxmcs commented on main.py
> +            logging.info("Something is wrong with the encryption key")
Вывести в лог сведения об исключении

2023-09-21 05:38 UTC, alxmcs commented on main.py
> +        except Exception:
Вывести в лог сведения об исключении

2023-09-21 05:38 UTC, alxmcs commented on main.py
> +        except ValueError:
Вывести в лог сведения об исключении

2023-09-21 05:38 UTC, alxmcs commented on requirements.txt
Файл пуст. Нужно сгенерировать его.

2023-09-24 20:43 UTC, lenayak commented
Необходимые изменения внесены.

2023-09-25 07:51 UTC, alxmcs requested changes

2023-09-25 07:51 UTC, alxmcs commented on main.py
> +            logging.exception("Something is wrong with the decryption key")
Здесь все еще не хватает вывода системного сообщения об ошибке

2023-09-25 07:51 UTC, alxmcs commented on main.py
> +                "Invalid key length: the key length should be 128/192/256."
Здесь все еще не указано значение, которое было указано пользователем  в качестве длины ключа

2023-09-25 13:46 UTC, lenayak commented
Необходимые изменения внесены.

2023-09-26 07:02 UTC, alxmcs requested changes

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Text not written")
Здесь какой смысл получать объект исключения, если потом никакая информация из него не логируется?
Залогируй свойства исключения

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Text not read")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Public key not saved")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Public key not saved")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Private key not loaded")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Private key not saved")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Symmetric key not saved")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Symmetric key not saved")
Аналогично

2023-09-26 07:02 UTC, alxmcs commented on load_info.py
> +        logging.info("Settings not loaded")
Аналогично

2023-09-26 07:27 UTC, lenayak commented
Необходимые изменения внесены.

2023-09-26 08:08 UTC, alxmcs approved these changes
Наконец-то

2023-09-26 08:08 UTC, closed without merging