complete
itsecd/isb-3 pull request #61
Opened 2023-09-19 17:42 UTC by Colnuwko

2023-09-20 09:48 UTC, alxmcs requested changes
Для начала:
* добавить описание к pr
* нормально назвать pr
* убрать из репозитория служебные файлы ide

2023-09-20 15:19 UTC, alxmcs requested changes
Общее замечание - варианта 15 не существует, их всего 9

2023-09-20 15:19 UTC, alxmcs commented on MainWindow.py
> +        main.point_1(16)
Это самое неподходящее именование для функции, которое можно было в принципе придумать

2023-09-20 15:19 UTC, alxmcs commented on script1.py
> +
Лишняя пустая строка

2023-09-20 15:19 UTC, alxmcs commented on script1.py
> +        return json_data[file_name]
Эта функция, а точнее эта ее строка снижают читаемость твоего кода до нуля, вкупе с нелогичными именованием настроек приложения, превращая его в спиздозное спагетти месиво с захардкоженными строками в качестве параметров других функций, при этом эти захардкоженные строки выглядят как относительные пути к файлам, хотя на самом деле являются ключами в словаре.
За распутывание этого клубка шизы мне должны присвоить степень доктора медицинских наук по клинической психиатрии.

Если бы этот код был частью продукта айти компании и другие люди были бы вынуждены его поддерживать/модифицировать, то его автора забили бы ногами насмерть на рабочем месте.

2023-09-22 09:57 UTC, alxmcs requested changes
Текущая версия кода мне нравится гораздо больше, осталось поправить некоторые мелочи

2023-09-22 09:57 UTC, alxmcs commented on Symmetric.py
> +
Многовато пустых строк в конце файла

2023-09-22 09:57 UTC, alxmcs commented on help_function.py
> +
Многовато пустых строк в конце файла

2023-09-22 09:57 UTC, alxmcs commented on main.py
> +
Многовато пустых строк в конце файла

2023-09-22 09:57 UTC, alxmcs commented on Asymmetric.py
Имена модулей пишутся строчными буквами согласно РЕР

2023-09-22 09:57 UTC, alxmcs commented on Hybrid.py
Имена модулей пишутся строчными буквами согласно РЕР

2023-09-22 09:57 UTC, alxmcs commented on Symmetric.py
Имена модулей пишутся строчными буквами согласно РЕР

2023-09-22 09:57 UTC, alxmcs commented on MainWindow.py
Имена модулей пишутся строчными буквами с андерскорами между словами согласно РЕР

2023-09-22 11:18 UTC, Colnuwko commented on decrypted/dec_file.txt
Служебные файлы удалил

2023-09-22 11:18 UTC, Colnuwko commented on encrypted/enc_file.txt
Служебные файлы удалил

2023-09-22 11:19 UTC, Colnuwko commented on settings.json
> +{"decrypted_file.txt": "C:/Users/\u0421\u043e\u043b\u043d\u044b\u0448\u043a\u043e/Desktop/IB_1/decrypted_file.txt", "encrypted_file.yaml": "C:/Users/\u0421\u043e\u043b\u043d\u044b\u0448\u043a\u043e/D
Именно поэтому я изменил их название, с учетом ваших рекомендаций

2023-09-22 11:20 UTC, Colnuwko commented on script3.py
> +from yaml import loader
удалил

2023-09-22 11:21 UTC, Colnuwko commented on script3.py
> +def decrypted_text(symmetric_key, path_to_enc_file, path_to_dec_file) -> str:
учтено, исправлено

2023-09-22 11:21 UTC, Colnuwko commented on script3.py
исправил

2023-09-22 11:23 UTC, Colnuwko commented on script1.py
> +### вЫПОЛНИМ 1 ПУНКТ
убал

2023-09-22 11:23 UTC, Colnuwko commented on script1.py
> +def load_settings():
переименовал

2023-09-22 11:24 UTC, Colnuwko commented on script2.py
> +                                                                    )
несуразный бред который появился в коде, теперь все немного иначе

2023-09-22 11:25 UTC, Colnuwko commented on script2.py
> +def encrypted_text_symmetric_algorithm(symmetric_key, bit):
и тайпхинты и докстринги присутствуют в каждой функции

2023-09-22 11:33 UTC, Colnuwko commented on script1.py
> +def encrypted_sym_key(sym_key, public_key, name):
функции каждого из алгоритмов помещены в отдельный именованный модуль
 Старался выносить каждые действия в отдельные функции

2023-09-22 11:34 UTC, Colnuwko commented on main.py
> +# See PyCharm help at https://www.jetbrains.com/help/pycharm/
убрал:)

2023-09-22 11:34 UTC, Colnuwko commented on main.py
> +# Press the green button in the gutter to run the script.
убрал

2023-09-22 11:34 UTC, Colnuwko commented on main.py
> +
не поверите, но тоже убрал

2023-09-22 11:35 UTC, Colnuwko commented on MainWindow.py
> +    """Других вариантов нет, код идеален, Успех в любом случае"""
с вашего позволения я оставлю эту строчку

2023-09-22 11:39 UTC, Colnuwko commented on MainWindow.py
> +    def reset_settings(self):
не совсем понял что нужно сделать с методом reset_settings
Но мое предположение, что нужно вынести этот метод за пределы класса, написав отдельную функцию

2023-09-22 11:45 UTC, Colnuwko commented on MainWindow.py
> +        main.point_1(16)
переименовал

2023-09-22 11:46 UTC, Colnuwko commented on script1.py
> +
убрал

2023-09-22 11:50 UTC, Colnuwko commented on script1.py
> +        return json_data[file_name]
Я не понимаю что с этой функцией не так
кроме возвращения пути до файла из settings.json она не делает ничего
Не знаю что в ней исправить
докстринги и тайпхинты добавил разумеется

2023-09-22 11:51 UTC, Colnuwko commented on Symmetric.py
> +
убрал во всех файлах

2023-09-22 11:51 UTC, Colnuwko commented on help_function.py
> +
аналогично

2023-09-22 11:51 UTC, Colnuwko commented on main.py
> +
аналогично

2023-09-22 11:55 UTC, Colnuwko commented on Asymmetric.py
переименовал

2023-09-22 11:56 UTC, Colnuwko commented on Hybrid.py
переименовал

2023-09-22 11:56 UTC, Colnuwko commented on Symmetric.py
переименовал

2023-09-22 11:56 UTC, Colnuwko commented on MainWindow.py
переименовал

2023-09-22 12:00 UTC, alxmcs approved these changes
Зачтено

2023-09-22 12:00 UTC, closed without merging