6212 Кропивенцев Юрий Дмитриевич Лаб. 3 Вар 7
itsecd/isb-3 pull request #7
Opened 2023-04-24 10:38 UTC by c0de1sl1fe

Результат данной лабораторной работы - гибридная криптосистема - будет сочетать в себе преимущества симметричных и асимметричных алгоритмов шифрования и в целом даже напоминать системы, использующиеся на практике.

Работать она будет следующим образом: сообщение шифруется при помощи симметричного алгоритма, а ключ симметричного алгоритма - ассиметричным. В качестве асимметричного алгоритма будет использоваться RSA, симметричный алгорим выбирается в соответствии с вариантом.

2023-04-24 13:08 UTC, alxmcs requested changes
Общие замечания:
* Убрать файлы виртуальной среды из репозитория,
* У большинства методов/функций нет нормального логинга,
* В исходниках огромное количество ненужных пустых строк, код тяжело воспринимать,
* Модуль `utils` нарушает srp, так как в нем намешан функционал, связанный как симметричным, так и с асимметричным шифрованием.

2023-04-25 12:24 UTC, c0de1sl1fe reviewed
done some fix

2023-04-26 11:39 UTC, alxmcs requested changes
Стало явно лучше

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +            # iv = os.urandom(16)
Закомменченный код убрать

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +        logging.error(str(e))
Сделать сообщение более информативным

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +        logging.error(str(e))
Сделать сообщение более информативным

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +            cipher = Cipher(algorithms.SM4(key), modes.CBC(iv))
Нет смысла держать файловый поток открытым, пока выполнятся все операции функции.
На строках 40-41 ты получил из нег овсе, что там было. Дальнейшие отступы в коде излишни.

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +        with open(pathOfData, 'r', encoding='utf-8') as data_in, open(name, 'wb') as data_out:
Здесь примерно аналогичная ситуация

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +        data_in.close
`.close` не нужен при использовании `with`

2023-04-26 11:39 UTC, alxmcs commented on utils_sym.py
> +        data_out.close
`.close` не нужен при использовании `with`

2023-04-26 11:39 UTC, alxmcs commented on utils_assym.py
> +        private_out.close
`.close` не нужен при использовании `with`

2023-04-26 11:39 UTC, alxmcs commented on utils_assym.py
> +        public_out.close
`.close` не нужен при использовании `with`

2023-04-26 11:39 UTC, alxmcs commented on utils_assym.py
> +        symm_out.close
`.close` не нужен при использовании `with`

2023-04-26 12:20 UTC, c0de1sl1fe reviewed
Вроде бы поправил

2023-04-26 13:54 UTC, alxmcs requested changes

2023-04-26 13:54 UTC, alxmcs commented on utils_assym.py
> +        symm_out.close
`.close` все еще на месте

2023-05-15 12:26 UTC, closed without merging